window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['ar_vr'] = [
  {rank:1,cat:'core',term:"空间计算",pro:"空间计算是Apple Vision Pro的核心技术，通过SLAM和传感器融合，将数字内容锚定在物理空间中，实现虚实融合交互。2023年苹果发布后，空间计算市场预计2030年达千亿美元。",ez:"让虚拟东西像真的一样放在你周围"},
  {rank:2,cat:'core',term:"VR一体机",pro:"VR一体机如Meta Quest 3集成计算、显示和追踪于头显，无需外接设备。2024年Quest 3销量超百万台，占据消费级VR市场主导。",ez:"戴上就能玩的独立VR头盔"},
  {rank:3,cat:'core',term:"MR混合现实",pro:"MR混合现实结合VR和AR，如Apple Vision Pro通过VST技术实现数字与物理世界实时融合。2024年MR设备出货量预计达800万台。",ez:"虚拟和现实混在一起分不清"},
  {rank:4,cat:'core',term:"AR眼镜",pro:"AR眼镜如Rokid Air Pro采用光学透视技术，在现实上叠加信息。2024年全球AR眼镜出货量约50万副，B端工业应用占60%。",ez:"像普通眼镜一样显示信息的眼镜"},
  {rank:5,cat:'core',term:"Apple Vision Pro",pro:"Apple Vision Pro是苹果2024年发布的空间计算头显，搭载M2+R1芯片，售价3499美元，首年销量预计50万台。",ez:"苹果那个卖三万五的头显"},
  {rank:6,cat:'core',term:"Meta Quest",pro:"Meta Quest系列是Meta旗下VR一体机，Quest 3售价499美元，2024年累计销量超2000万台，主导消费VR市场。",ez:"脸书出的VR头盔，销量最大"},
  {rank:7,cat:'core',term:"字节PICO",pro:"PICO是字节跳动旗下VR品牌，PICO 4售价4299元，2024年国内市场份额超40%，主打VR健身和视频。",ez:"字节跳动的VR头盔，国内卖得好"},
  {rank:8,cat:'core',term:"Pimax",pro:"Pimax以超宽视场角VR头显闻名，如Pimax Crystal支持200°FOV，分辨率达2880×2880，售价1599美元，面向高端玩家。",ez:"视野超宽的VR头盔，发烧友最爱"},
  {rank:9,cat:'core',term:"Rokid",pro:"Rokid是国产AR眼镜厂商，Rokid Air Pro重量仅83克，支持语音交互，2024年出货量超10万副，主要面向文旅和工业。",ez:"国产AR眼镜，轻便好用"},
  {rank:10,cat:'core',term:"XREAL",pro:"XREAL（原Nreal）是AR眼镜领��企业，XREAL Air 2重量72克，2024年全球出货量超20万副，与宝马等车企合作。",ez:"最轻的AR眼镜之一，和汽车合作"},
  {rank:11,cat:'core',term:"VST透视",pro:"VST（Video See-Through）通过摄像头捕捉现实画面并显示在屏幕上，实现MR效果。Apple Vision Pro采用12颗摄像头，延迟仅12ms。",ez:"用摄像头看现实，再显示到屏幕"},
  {rank:12,cat:'core',term:"OST透视",pro:"OST（Optical See-Through）通过光学透镜直接叠加数字信息，如HoloLens 2采用光波导，透光率约80%，适合AR眼镜。",ez:"直接透过镜片看到虚拟信息"},
  {rank:13,cat:'core',term:"视场角(FOV)",pro:"视场角决定沉浸感，人眼水平FOV约200°，Pimax Crystal达200°，而Apple Vision Pro约100°，Quest 3为110°。",ez:"视野有多宽，越大越沉浸"},
  {rank:14,cat:'core',term:"瞳距调节(IPD)",pro:"瞳距调节适配不同用户，Quest 3支持58-71mm机械调节，Apple Vision Pro采用电动调节，确保图像清晰。",ez:"调整镜头距离适应你的眼距"},
  {rank:15,cat:'core',term:"眼动追踪",pro:"眼动追踪通过红外摄像头捕捉眼球运动，Apple Vision Pro和Quest Pro支持，用于注视点渲染和交互，精度达0.5°。",ez:"头盔能知道你眼睛在看哪里"},
  {rank:16,cat:'tech',term:"Pancake透镜",pro:"Pancake透镜通过折叠光路缩短VR头显厚度，如PICO 4采用后厚度仅35mm，相比菲涅尔透镜减薄50%。",ez:"让VR头盔变薄的透镜技术"},
  {rank:17,cat:'tech',term:"Micro-OLED",pro:"Micro-OLED用于高端VR/AR，如Apple Vision Pro搭载两块2300万像素Micro-OLED，像素密度达3400PPI，亮度超5000nit。",ez:"超高清微型屏幕，像素密度极高"},
  {rank:18,cat:'tech',term:"光波导",pro:"光波导是AR眼镜主流光学方案，如Rokid Air采用Birdbath，而XREAL Air用光波导，视场角约46°，透光率80%。",ez:"AR眼镜里传输光线的技术"},
  {rank:19,cat:'tech',term:"SLAM定位",pro:"SLAM（即时定位与地图构建）是AR/VR空间定位基础，如HoloLens 2采用视觉+惯性SLAM，定位精度达厘米级，延迟低于20ms。",ez:"让设备知道自己在哪里的技术"},
  {rank:20,cat:'tech',term:"注视点渲染",pro:"注视点渲染根据眼动追踪降低外围分辨率，节省算力。PSVR 2采用该技术，渲染效率提升约50%，功耗降低30%。",ez:"只看清你盯着的地方，省电"},
  {rank:21,cat:'tech',term:"手势识别",pro:"手势识别通过摄像头或手套捕捉手部动作，如Quest 3支持裸手追踪，识别26个关节点，延迟低于10ms。",ez:"不用手柄，用手直接操作"},
  {rank:22,cat:'tech',term:"6DoF追踪",pro:"6DoF追踪提供前后、上下、左右及旋转自由度，如PICO 4采用inside-out追踪，定位精度0.1mm，支持10×10米空间。",ez:"在三维空间里自由移动和旋转"},
  {rank:23,cat:'tech',term:"瞳距调节(IPD)",pro:"瞳距调节适配不同用户，Quest 3支持58-71mm机械调节，Apple Vision Pro采用电动调节，确保图像清晰。",ez:"调整镜头距离适应你的眼距"},
  {rank:24,cat:'tech',term:"触觉反馈",pro:"触觉反馈通过震动或力反馈增强沉浸感，如PSVR 2手柄支持自适应扳机，提供0-100级阻力，提升交互真实感。",ez:"手柄震动或按钮有阻力，像真的一样"},
  {rank:25,cat:'tech',term:"眼动追踪",pro:"眼动追踪通过红外摄像头捕捉眼球运动，Apple Vision Pro和Quest Pro支持，用于注视点渲染和交互，精度达0.5°。",ez:"头盔能知道你眼睛在看哪里"},
  {rank:26,cat:'biz',term:"硬件订阅",pro:"硬件订阅如Meta Quest+每月9.99美元提供游戏和配件，或苹果Vision Pro租赁服务，降低用户门槛，提升复购率。",ez:"租头盔用，每月付钱"},
  {rank:27,cat:'biz',term:"内容分成",pro:"内容分成是平台主要收入，如Meta Quest Store抽取30%分成，2024年VR内容收入超20亿美元，游戏占70%。",ez:"平台抽成，开发者拿七成"},
  {rank:28,cat:'biz',term:"B端定制",pro:"B端定制如微软HoloLens用于工业培训，2024年企业AR市场达30亿美元，波音用AR眼镜提升装配效率30%。",ez:"给公司做专用AR/VR方案"},
  {rank:29,cat:'biz',term:"广告植入",pro:"广告植入在VR/AR中兴起，如Meta Horizon Worlds内品牌广告，2024年VR广告支出达5亿美元，点击率比传统高3倍。",ez:"在虚拟世界里放广告"},
  {rank:30,cat:'biz',term:"虚拟社交",pro:"虚拟社交如Meta Horizon Worlds月活超30万，用户通过化身互动，2024年虚拟社交市场规模达20亿美元。",ez:"在VR里和朋友聚会聊天"},
  {rank:31,cat:'biz',term:"远程协作",pro:"远程协作如Spatial平台支持多人AR会议，2024年企业用AR协作工具市场达15亿美元，微软Mesh支持Teams集成。",ez:"戴AR眼镜远程一起工作"},
  {rank:32,cat:'biz',term:"健身应用",pro:"健身应用如Supernatural VR订阅费每月19美元，2024年VR健身用户超500万，PICO 4推出健身课程，消耗卡路里比跑步多30%。",ez:"在VR里锻炼身体"},
  {rank:33,cat:'biz',term:"影视体验",pro:"影视体验如Apple Vision Pro支持3D电影，Disney+推出沉浸式内容，2024年VR影视收入达8亿美元，用户平均观看时长45分钟。",ez:"用VR看电影，像在电影院"},
  {rank:34,cat:'biz',term:"教育培训",pro:"教育培训如Labster VR模拟实验室，2024年VR教育市场达10亿美元，学生通过VR学习效率提升40%。",ez:"用VR上课，学得更快"},
  {rank:35,cat:'biz',term:"游戏内购",pro:"游戏内购如《Beat Saber》付费曲包每包10美元，2024年VR游戏内购收入占整体30%，用户付费意愿高。",ez:"在VR游戏里买道具或歌曲"},
  {rank:36,cat:'finance',term:"ARPU值",pro:"ARPU值指每用户平均收入，Meta Quest平台ARPU约120美元/年，其中游戏消费占80%，硬件利润较低。",ez:"每个用户平均花多少钱"},
  {rank:37,cat:'finance',term:"毛利率",pro:"毛利率反映硬件盈利能力，Apple Vision Pro物料成本约1500美元，售价3499美元，毛利率约57%，但研发成本高。",ez:"卖一个赚多少钱的比例"},
  {rank:38,cat:'finance',term:"研发投入占比",pro:"研发投入占比高，Meta Reality Labs 2024年研发支出超150亿美元，占Meta总营收20%，用于VR/AR技术。",ez:"公司花多少钱搞研发"},
  {rank:39,cat:'finance',term:"出货量",pro:"出货量是行业关键指标，2024年全球VR/AR头显出货量约1200万台，其中VR占80%，AR增速快达40%。",ez:"一年卖了多少台设备"},
  {rank:40,cat:'finance',term:"用户留存率",pro:"用户留存率决定长期价值，Quest 3首月留存率约70%，但半年后降至40%，内容粘性仍是挑战。",ez:"买了之后还继续用的比例"}
];
