window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['advertising'] = [
  {rank:1,cat:'core',term:"程序化广告",pro:"通过自动化系统（如DSP、SSP）实时竞价购买广告位，2023年中国程序化广告市场规模超800亿元，占数字广告60%以上。",ez:"机器自动买广告"},
  {rank:2,cat:'core',term:"DSP",pro:"需求方平台，广告主通过它实时竞价购买广告库存，如巨量引擎、腾讯广告。2022年全球DSP支出达500亿美元。",ez:"广告主买流量的工具"},
  {rank:3,cat:'core',term:"SSP",pro:"供应方平台，帮助媒体管理广告库存并接入DSP，如Google Ad Manager。全球SSP市场2023年规模约120亿美元。",ez:"媒体卖广告位的平台"},
  {rank:4,cat:'core',term:"DMP",pro:"数据管理平台，整合用户数据用于精准定向，如阿里达摩盘。2023年全球DMP市场达25亿美元。",ez:"用户数据仓库"},
  {rank:5,cat:'core',term:"信息流广告",pro:"嵌入内容流中的原生广告，如抖音、微信朋友圈广告。2023年中国信息流广告占移动广告份额超40%。",ez:"刷到的广告"},
  {rank:6,cat:'core',term:"效果广告",pro:"以转化（如点击、下载）为计费目标的广告，如百度竞价排名。2023年效果广告占中国互联网广告70%以上。",ez:"按效果付钱"},
  {rank:7,cat:'core',term:"品牌广告",pro:"以提升品牌认知为目标的广告，如电视广告、开屏广告。2023年全球品牌广告支出约4000亿美元。",ez:"刷脸广告"},
  {rank:8,cat:'core',term:"RTB",pro:"实时竞价，广告库存通过拍卖在毫秒内售出，如Google Ad Exchange。RTB占程序化广告60%以上。",ez:"秒拍广告位"},
  {rank:9,cat:'core',term:"CTR",pro:"点击率，广告点击次数/展示次数，行业平均约0.5%-2%。",ez:"广告被点概率"},
  {rank:10,cat:'core',term:"转化率",pro:"用户完成目标动作（如购买）的比例，电商广告平均转化率约2%-5%。",ez:"看完买了的比例"},
  {rank:11,cat:'core',term:"千次展示成本",pro:"CPM，广告每千次展示费用，信息流CPM约20-100元。",ez:"一千次曝光多少钱"},
  {rank:12,cat:'core',term:"单次点击成本",pro:"CPC，每次点击费用，搜索广告CPC约1-10元。",ez:"点一下多少钱"},
  {rank:13,cat:'core',term:"单次行动成本",pro:"CPA，每次转化（如注册）费用，应用下载CPA约10-50元。",ez:"一个动作多少钱"},
  {rank:14,cat:'core',term:"LTV",pro:"用户生命周期价值，预测用户长期贡献，如游戏用户LTV平均50元。",ez:"一个用户值多少"},
  {rank:15,cat:'core',term:"ROI",pro:"投资回报率，广告ROI=收入/成本，健康值>3。",ez:"投一块赚几块"},
  {rank:16,cat:'tech',term:"Cookie",pro:"浏览器存储的用户标识，用于追踪和定向，第三方Cookie即将淘汰（Chrome计划2024年禁用）。",ez:"上网小标签"},
  {rank:17,cat:'tech',term:"设备ID",pro:"移动设备唯一标识，如IDFA（苹果）、OAID（安卓），用于跨应用追踪。",ez:"手机身份证"},
  {rank:18,cat:'tech',term:"归因模型",pro:"分配转化功劳的规则，如最后点击归因、多触点归因。2023年行业趋向数据驱动归因。",ez:"功劳怎么分"},
  {rank:19,cat:'tech',term:"Look-alike",pro:"相似人群扩展，基于种子用户找到类似人群，如Facebook的Lookalike Audience。",ez:"找相似的人"},
  {rank:20,cat:'tech',term:"动态创意优化",pro:"DCO，根据用户实时生成个性化广告，如Criteo的个性化banner。",ez:"广告千人千面"},
  {rank:21,cat:'tech',term:"广告验证",pro:"监测广告可见性、品牌安全，如IAS、Moat。2023年全球广告验证市场达50亿美元。",ez:"广告有没有被看到"},
  {rank:22,cat:'tech',term:"SDK",pro:"软件开发工具包，嵌入App实现广告功能，如穿山甲SDK。",ez:"App里装广告模块"},
  {rank:23,cat:'tech',term:"API",pro:"应用程序接口，用于广告系统对接，如Google Ads API。",ez:"系统间传数据"},
  {rank:24,cat:'tech',term:"A/B测试",pro:"对比实验，测试不同广告版本效果，如Facebook的A/B测试工具。",ez:"哪个广告好"},
  {rank:25,cat:'tech',term:"频次控制",pro:"限制用户看到广告的次数，避免骚扰，一般建议3-5次/天。",ez:"别让用户看烦了"},
  {rank:26,cat:'biz',term:"巨量引擎",pro:"字节跳动旗下广告平台，整合抖音、今日头条等资源，2023年收入超2000亿元。",ez:"字节的广告系统"},
  {rank:27,cat:'biz',term:"腾讯广告",pro:"腾讯的广告平台，覆盖微信、QQ、腾讯视频，2023年收入约1000亿元。",ez:"腾讯的广告系统"},
  {rank:28,cat:'biz',term:"百度营销",pro:"百度旗下营销平台，以搜索广告为主，2023年收入约700亿元。",ez:"百度的广告系统"},
  {rank:29,cat:'biz',term:"小红书种草",pro:"通过KOL推荐产品，影响用户决策，2023年小红书广告收入约200亿元。",ez:"博主带货"},
  {rank:30,cat:'biz',term:"抖音千川",pro:"抖音电商广告平台，支持直播带货，2023年千川GMV超万亿。",ez:"抖音卖货广告"},
  {rank:31,cat:'biz',term:"联盟广告",pro:"广告主通过联盟网络投放，媒体分成，如Google AdSense。",ez:"网站放广告赚钱"},
  {rank:32,cat:'biz',term:"KOL营销",pro:"与关键意见领袖合作推广，2023年中国KOL营销市场规模超1000亿元。",ez:"找网红打广告"},
  {rank:33,cat:'biz',term:"私域流量",pro:"品牌自有用户池，如微信群、公众号，复购率比公域高3-5倍。",ez:"自己的粉丝"},
  {rank:34,cat:'biz',term:"公域流量",pro:"平台公共流量，如抖音推荐页，需付费获取。",ez:"平台的流量"},
  {rank:35,cat:'biz',term:"品效合一",pro:"品牌广告与效果广告结合，如抖音开屏+信息流，提升转化。",ez:"既要名又要利"},
  {rank:36,cat:'finance',term:"广告收入",pro:"媒体通过广告获得的收入，如Google 2023年广告收入2370亿美元。",ez:"卖广告赚的钱"},
  {rank:37,cat:'finance',term:"ARPU",pro:"每用户平均收入，如游戏公司ARPU 50元/月。",ez:"每个用户贡献多少"},
  {rank:38,cat:'finance',term:"毛利率",pro:"广告业务毛利率，如百度广告毛利率约70%。",ez:"赚的钱扣掉成本"},
  {rank:39,cat:'finance',term:"客户获取成本",pro:"CAC，获取一个新客户的平均成本，SaaS行业CAC约1000元。",ez:"拉一个新客户花多少"},
  {rank:40,cat:'finance',term:"留存率",pro:"用户持续使用比例，如电商App次日留存率40%以上。",ez:"用户留不留"}
];
