window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['bigdata'] = [
  {rank:1,cat:'core',term:"大数据",pro:"大数据是指无法用传统数据处理工具处理的海量、高速、多样化的数据集合。全球数据量预计2025年达175ZB，需分布式系统处理。",ez:"海量数据，传统工具搞不定"},
  {rank:2,cat:'core',term:"Hadoop",pro:"Hadoop是Apache开源的分布式存储与计算框架，核心包括HDFS和MapReduce，可处理PB级数据。Yahoo曾用其处理超10PB数据。",ez:"大数据界的瑞士军刀"},
  {rank:3,cat:'core',term:"Spark",pro:"Spark是Apache开源的统一分析引擎，支持内存计算，比Hadoop MapReduce快100倍。Databricks基于Spark构建，估值超400亿美元。",ez:"内存计算，快到飞起"},
  {rank:4,cat:'core',term:"数据仓库",pro:"数据仓库是面向分析的集成化数据存储系统，如Snowflake支持弹性扩展，2024年营收超30亿美元。典型架构包括星型和雪花型。",ez:"企业数据大仓库"},
  {rank:5,cat:'core',term:"数据湖",pro:"数据湖以原始格式存储海量结构化与非结构化数据，如AWS S3作为数据湖存储，支持分析。Gartner预测2025年80%企业将采用。",ez:"啥数据都往里扔的湖"},
  {rank:6,cat:'core',term:"湖仓一体",pro:"湖仓一体融合数据湖与数据仓库优势，如Databricks的Delta Lake支持ACID事务。Gartner称其为下一代数据架构。",ez:"湖和仓库合体"},
  {rank:7,cat:'core',term:"ETL",pro:"ETL（抽取、转换、加载）是数据集成核心流程，如Informatica PowerCenter每天处理数十亿记录。云ETL工具Fivetran年营收超5亿美元。",ez:"数据搬家并整理"},
  {rank:8,cat:'core',term:"实时计算",pro:"实时计算处理毫秒级数据流，如Apache Flink支持事件时间处理。阿里双11实时计算峰值每秒处理40亿条消息。",ez:"数据秒级处理"},
  {rank:9,cat:'core',term:"OLAP",pro:"OLAP（联机分析处理）支持多维分析，如ClickHouse单机查询性能超传统数据库100倍。典型应用包括BI报表。",ez:"多维数据分析"},
  {rank:10,cat:'core',term:"数据挖掘",pro:"数据挖掘从大量数据中提取隐含模式，如关联规则Apriori算法。Netflix用其推荐系统节省10亿美元/年。",ez:"从数据里挖金子"},
  {rank:11,cat:'core',term:"机器学习",pro:"机器学习是AI核心，通过数据训练模型。Google TensorFlow被用于超1亿个模型训练。大数据提供训练数据基础。",ez:"让机器自己学习"},
  {rank:12,cat:'core',term:"云计算",pro:"云计算提供按需计算资源，如AWS、Azure、GCP。大数据分析常依赖云弹性，AWS EMR可快速启动数千节点集群。",ez:"租用服务器算数据"},
  {rank:13,cat:'core',term:"数据治理",pro:"数据治理管理数据资产，包括质量、安全、合规。GDPR规定违规罚款达全球营收4%。企业需建立数据目录。",ez:"管好数据资产"},
  {rank:14,cat:'core',term:"数据安全",pro:"数据安全保护数据免受泄露，如加密、访问控制。2023年全球数据泄露平均成本445万美元。",ez:"保护数据不泄露"},
  {rank:15,cat:'core',term:"数据可视化",pro:"数据可视化用图表展示数据，如Tableau被Salesforce以157亿美元收购。有效可视化可提升决策效率5倍。",ez:"把数据画成图"},
  {rank:16,cat:'tech',term:"Kafka",pro:"Kafka是Apache开源的分布式消息队列，每秒可处���百万级消息。LinkedIn用其处理超1万亿条消息/天。",ez:"数据高速公路"},
  {rank:17,cat:'tech',term:"Flink",pro:"Flink是Apache开源的流处理框架，支持精确一次语义。阿里巴巴基于Flink构建实时计算平台，处理超40亿条/秒。",ez:"流数据处理神器"},
  {rank:18,cat:'tech',term:"HDFS",pro:"HDFS是Hadoop分布式文件系统，默认块大小128MB，可存储PB级数据。典型集群规模超1000节点。",ez:"分布式文件系统"},
  {rank:19,cat:'tech',term:"NoSQL",pro:"NoSQL数据库非关系型，如MongoDB文档型，Cassandra列族型。MongoDB 2024年营收超20亿美元。",ez:"非关系型数据库"},
  {rank:20,cat:'tech',term:"MapReduce",pro:"MapReduce是Hadoop的并行计算模型，分Map和Reduce阶段。Google最初用于处理超20PB网页索引。",ez:"分而治之计算"},
  {rank:21,cat:'tech',term:"数据流",pro:"数据流是连续不断的数据序列，如IoT传感器数据。Flink和Kafka Streams支持流式处理。",ez:"持续流动的数据"},
  {rank:22,cat:'tech',term:"数据分区",pro:"数据分区将大表分成小物理块，如Hive按日期分区，可提升查询性能10倍以上。",ez:"把数据分块存储"},
  {rank:23,cat:'tech',term:"数据压缩",pro:"数据压缩减少存储空间，如Snappy压缩比约2:1，Parquet列式存储压缩比达10:1。",ez:"给数据瘦身"},
  {rank:24,cat:'tech',term:"数据序列化",pro:"数据序列化将对象转为字节流，如Avro、Protobuf。Avro在Hadoop生态广泛使用，支持模式演化。",ez:"对象转字节流"},
  {rank:25,cat:'tech',term:"数据目录",pro:"数据目录管理元数据，如Apache Atlas、Collibra。Collibra估值超50亿美元。",ez:"数据的说明书"},
  {rank:26,cat:'biz',term:"数据中台",pro:"数据中台是企业数据共享平台，如阿里数据中台支撑双11。建设成本通常超千万，但可提升数据复用率50%。",ez:"企业数据共享中心"},
  {rank:27,cat:'biz',term:"数据湖仓",pro:"数据湖仓结合湖和仓，如Databricks Lakehouse平台。Snowflake也支持类似架构。",ez:"湖和仓融合"},
  {rank:28,cat:'biz',term:"数据即服务",pro:"数据即服务（DaaS）按需提供数据，如Snowflake按计算和存储计费。2024年DaaS市场规模超100亿美元。",ez:"数据像水一样卖"},
  {rank:29,cat:'biz',term:"数据变现",pro:"数据变现通过数据产生收入，如广告���向。Facebook 2023年广告收入超1300亿美元。",ez:"用数据赚钱"},
  {rank:30,cat:'biz',term:"数据产品",pro:"数据产品是封装数据价值的应用，如信用评分。Experian年营收超50亿美元。",ez:"数据做成的商品"},
  {rank:31,cat:'biz',term:"数据中台",pro:"数据中台是企业数据共享平台，如阿里数据中台支撑双11。建设成本通常超千万，但可提升数据复用率50%。",ez:"企业数据共享中心"},
  {rank:32,cat:'biz',term:"数据治理平台",pro:"数据治理平台如Collibra、Alation，帮助管理数据资产。Alation估值超50亿美元。",ez:"管数据的软件"},
  {rank:33,cat:'biz',term:"数据仓库即服务",pro:"数据仓库即服务（DWaaS）如Snowflake、Amazon Redshift。Snowflake 2024年营收超30亿美元。",ez:"租用数据仓库"},
  {rank:34,cat:'biz',term:"数据湖即服务",pro:"数据湖即服务如AWS Lake Formation，简化数据湖搭建。Gartner预测2025年50%数据湖将部署在云上。",ez:"租用数据湖"},
  {rank:35,cat:'biz',term:"数据集成平台",pro:"数据集成平台如Fivetran、Stitch，自动化ETL。Fivetran年营收超5亿美元。",ez:"自动数据搬运工"},
  {rank:36,cat:'fin',term:"数据存储成本",pro:"数据存储成本包括硬件、云服务。AWS S3标准存储约0.023美元/GB/月，PB级年存储成本超20万美元。",ez:"存数据要花多少钱"},
  {rank:37,cat:'fin',term:"数据处理成本",pro:"数据处理成本如Spark集群计算费用。AWS EMR每节点每小时约0.1-0.5美元。",ez:"算数据要花多少钱"},
  {rank:38,cat:'fin',term:"数据质量成本",pro:"数据质量成本因低质量数据导致的损失。Gartner估计每年达1500万美元。",ez:"数据不准亏的钱"},
  {rank:39,cat:'fin',term:"数据投资回报率",pro:"数据投资回报率（ROI）衡量数据项目收益。麦肯锡显示数据驱动企业利润率提升20%。",ez:"投数据赚多少"},
  {rank:40,cat:'fin',term:"数据资产估值",pro:"数据资产估值评估数据价值，如公司数据资产占总资产比例。2023年数据资产入表试点启动。",ez:"数据值多少钱"}
];
