window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['cloud'] = [
  {rank:1,cat:'core',term:"IaaS",pro:"基础设施即服务，提供虚拟化计算资源，如AWS EC2，2023年全球市场规模超1300亿美元。",ez:"租用服务器和存储"},
  {rank:2,cat:'core',term:"PaaS",pro:"平台即服务，提供应用开发和部署平台，如Google App Engine，可减少70%开发环境配置时间。",ez:"租用开发平台"},
  {rank:3,cat:'core',term:"SaaS",pro:"软件即服务，通过互联网提供软件应用，如Salesforce，占云服务市场60%以上份额。",ez:"租用软件用"},
  {rank:4,cat:'core',term:"公有云",pro:"第三方提供商通过互联网向公众提供的云服务，如AWS、Azure，2023年全球支出超5000亿美元。",ez:"用公共云服务"},
  {rank:5,cat:'core',term:"私有云",pro:"为单一组织专有而构建的云环境，如VMware vSphere，可提升数据安全性和合规性，成本比公有云高30%。",ez:"自己用的云"},
  {rank:6,cat:'core',term:"混合云",pro:"结合公有云和私有云的架构，如AWS Outposts，允许数据和应用在两者间共享，企业采用率超80%。",ez:"公有+私有云"},
  {rank:7,cat:'core',term:"多云",pro:"使用多个云服务提供商，如同时用AWS和Azure，避免供应商锁定，企业多云策略采用率超90%。",ez:"用多个云"},
  {rank:8,cat:'core',term:"虚拟化",pro:"将物理资源抽象为虚拟资源的技术，如VMware ESXi，可提高服务器利用率从15%到80%。",ez:"一台变多台"},
  {rank:9,cat:'core',term:"弹性伸缩",pro:"根据负载自动调整资源，如AWS Auto Scaling，可节省成本高达50%。",ez:"自动扩缩容"},
  {rank:10,cat:'core',term:"负载均衡",pro:"分发流量到多个服务器，如AWS ELB，确保高可用性，延迟降低至10ms内。",ez:"分流防崩"},
  {rank:11,cat:'core',term:"可用区",pro:"云服务商的数据中心区域，如AWS有多个可用区，故障隔离，可用性目标达99.99%。",ez:"机房分区"},
  {rank:12,cat:'core',term:"CDN",pro:"内容分发网络，如CloudFront，将内容缓存到边缘节点，加速访问，可减少延迟50%以上。",ez:"就近取内容"},
  {rank:13,cat:'core',term:"边缘计算",pro:"在靠近数据源处处理数据，如AWS Wavelength，延迟低至1ms，适用于IoT和5G场景。",ez:"靠近用户算"},
  {rank:14,cat:'core',term:"Serverless",pro:"无服务器计算，如AWS Lambda，按需执行代码，无需管理服务器，可节省运维成本90%。",ez:"只管写代码"},
  {rank:15,cat:'core',term:"容器化",pro:"使用容器打包应用，如Docker，启动时间秒级，资源利用率比虚拟机高20%。",ez:"轻量级打包"},
  {rank:16,cat:'tech',term:"Kubernetes",pro:"容器编排平台，如Google Kubernetes Engine，可管理数千个容器，部署效率提升10倍。",ez:"容器管家"},
  {rank:17,cat:'tech',term:"Docker",pro:"容器引擎，打包应用及其依赖，如Docker Hub有超100亿次镜像下载。",ez:"装应用的盒子"},
  {rank:18,cat:'tech',term:"微服务",pro:"将应用拆分为独立服务，如Netflix使用微服务架构，部署频率提升200%。",ez:"拆成小块"},
  {rank:19,cat:'tech',term:"API网关",pro:"管理API请求的入口，如AWS API Gateway，可处理每秒数十万请求。",ez:"API大门"},
  {rank:20,cat:'tech',term:"云原生",pro:"基于容器、微服务、DevOps的云上应用开发方式，如CNCF定义，企业采用率超50%。",ez:"为云而生"},
  {rank:21,cat:'tech',term:"DevOps",pro:"开发运维一体化，如Jenkins CI/CD，可缩短部署周期从月到天。",ez:"开发运维一起"},
  {rank:22,cat:'tech',term:"基础设施即代码",pro:"用代码管理基础设施，如Terraform，部署时间从小时降至分钟。",ez:"代码管服务器"},
  {rank:23,cat:'tech',term:"对象存储",pro:"存储非结构化数据，如AWS S3，存储超200万亿对象，持久性达99.999999999%。",ez:"存文件"},
  {rank:24,cat:'tech',term:"块存储",pro:"提供原始块设备，如AWS EBS，延迟低至1ms，适用于数据库。",ez:"硬盘挂载"},
  {rank:25,cat:'tech',term:"VPC",pro:"虚拟私有云，如AWS VPC，可隔离网络，创建子网和路由表。",ez:"云上局域网"},
  {rank:26,cat:'biz',term:"AWS",pro:"亚马逊云服务，全球市场份额超30%，2023年营收超900亿美元。",ez:"亚马逊云"},
  {rank:27,cat:'biz',term:"Azure",pro:"微软云服务，全球第二，市场份额约25%，与Office 365深度集成。",ez:"微软云"},
  {rank:28,cat:'biz',term:"阿里云",pro:"阿里巴巴云服务，中国市场份额第一，超35%，2023年营收超1000亿人民币。",ez:"阿里云"},
  {rank:29,cat:'biz',term:"腾讯云",pro:"腾讯云服务，中国市场份额第二，约15%，游戏和视频领域优势明显。",ez:"腾讯云"},
  {rank:30,cat:'biz',term:"Google Cloud",pro:"谷歌云服务，全球第三，在AI和数据分析领域领先，2023年营收超300亿美元。",ez:"谷歌云"},
  {rank:31,cat:'biz',term:"按需付费",pro:"根据使用量付费，如AWS按小时计费，可降低初期成本，灵活匹配需求。",ez:"用多少付多少"},
  {rank:32,cat:'biz',term:"预留实例",pro:"预付费锁定折扣，如AWS预留实例可节省高达72%费用。",ez:"预付费省钱"},
  {rank:33,cat:'biz',term:"SLA",pro:"服务等级协议，如AWS承诺99.99%可用性，未达标可获赔偿。",ez:"服务保障"},
  {rank:34,cat:'biz',term:"云迁移",pro:"将本地应用迁移到云，如AWS Migration Hub，可降低TCO 30%。",ez:"搬到云上"},
  {rank:35,cat:'biz',term:"云安全",pro:"云环境安全措施，如AWS Shield防护DDoS，可抵御T级攻击。",ez:"云上防护"},
  {rank:36,cat:'fin',term:"CAPEX",pro:"资本支出，传统IT需前期大量投入，云计算转为OPEX，可降低CAPEX 80%。",ez:"买硬件钱"},
  {rank:37,cat:'fin',term:"OPEX",pro:"运营支出，云计算按需付费为OPEX，企业可灵活调整预算。",ez:"日常开销"},
  {rank:38,cat:'fin',term:"TCO",pro:"总拥有成本，包括硬件、软件、运维，云迁移可降低TCO 30-50%。",ez:"总成本"},
  {rank:39,cat:'fin',term:"ARPU",pro:"每用户平均收入，云服务商如AWS ARPU持续增长，2023年超3000美元/年。",ez:"每用户收入"},
  {rank:40,cat:'fin',term:"毛利率",pro:"云服务毛利率，AWS约60%，高于传统IT，规模效应显著。",ez:"赚钱比例"}
];
