window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['chiplet'] = [
  {rank:1,cat:'core',term:"Chiplet",pro:"一种芯片设计方法，将大型单芯片拆分为多个小型芯片（芯粒），通过先进封装技术互联，形成完整系统。AMD MI300采用13个Chiplet，性能提升显著。",ez:"把大芯片拆成小积木拼起来"},
  {rank:2,cat:'core',term:"UCIe协议",pro:"Universal Chiplet Interconnect Express，开放标准协议，定义Chiplet间物理层、链路层等，支持2D/2.5D/3D封装，目标实现多供应商Chiplet互操作。",ez:"芯片间通信的通用语言"},
  {rank:3,cat:'core',term:"2.5D封装",pro:"通过硅中介层（Interposer）将多个芯片并排放置，实现高密度互连。典型如台积电CoWoS，用于NVIDIA GPU，带宽可达TB/s级。",ez:"芯片平铺在硅板上连起来"},
  {rank:4,cat:'core',term:"3D堆叠",pro:"将多个芯片垂直堆叠，通过硅通孔（TSV）互联，缩短连线、提升带宽。Intel Foveros技术实现逻辑芯片堆叠，AMD 3D V-Cache堆叠SRAM。",ez:"芯片叠罗汉，省地方又快"},
  {rank:5,cat:'core',term:"CoWoS",pro:"台积电2.5D封装技术，Chip-on-Wafer-on-Substrate，将芯片置于硅中介层再封装。广泛用于AI芯片，如NVIDIA A100/H100，集成HBM内存。",ez:"台积电的芯片拼盘技术"},
  {rank:6,cat:'core',term:"先进封装",pro:"超越传统封装的互连技术，包括2.5D/3D封装、扇出型等，实现更高密度、带宽和能效。2023年市场规模约400亿美元，年增长10%以上。",ez:"把芯片装得更高级的方法"},
  {rank:7,cat:'core',term:"异构集成",pro:"将不同工艺、功能的芯片（如逻辑、存储、模拟）集成在同一封装内，优化性能与成本。AMD MI300集成CPU和GPU Chiplet。",ez:"不同功能的芯片拼一起"},
  {rank:8,cat:'core',term:"芯粒",pro:"Chiplet的中文译名，指功能完整的小芯片，通过互联组成系统。每个芯粒可用不同工艺制造，如7nm逻辑芯粒搭配14nm I/O芯粒。",ez:"小芯片，积木块"},
  {rank:9,cat:'core',term:"Die-to-Die互联",pro:"芯片间直接互连技术，通过UCIe、BoW等协议，实现高带宽低延迟。典型速率达16Gbps/pin，功耗低于0.5pJ/bit。",ez:"芯片间直连高速路"},
  {rank:10,cat:'core',term:"硅中介层",pro:"2.5D封装中用于承载芯片的硅片，包含精细布线层和TSV，实现芯片间高密度互连。线宽可达0.5μm，层数可达10层以上。",ez:"芯片底下的硅基板"},
  {rank:11,cat:'core',term:"TSV",pro:"Through Silicon Via，硅通孔，垂直贯穿硅片的导电通道，用于3D堆叠芯片间互联。直径通常5-10μm，深度50-100μm。",ez:"硅片上的垂直小孔"},
  {rank:12,cat:'core',term:"Foveros",pro:"Intel的3D封装技术，将逻辑芯片堆叠，实现高性能计算。用于Lakefield处理器，顶部计算芯片10nm，底部基础芯片22nm。",ez:"Intel的芯片叠叠乐"},
  {rank:13,cat:'core',term:"AMD MI300",pro:"AMD数据中心APU，集成13个Chiplet（CPU+GPU+IO），采用3D堆叠和2.5D封装，晶体管数1460亿，用于AI训练。",ez:"AMD的超级芯片拼盘"},
  {rank:14,cat:'core',term:"Graphcore",pro:"英国AI芯片公司，其IPU采用Chiplet架构，通过2.5D封装集成多个处理器和内存，支持大规模并行计算。",ez:"英国AI芯片公司，用积木设计"},
  {rank:15,cat:'core',term:"小芯片架构",pro:"将复杂SoC分解为多个小芯片，通过封装集成，降低设计复杂度、提高良率。典型如AMD Zen架构，CCD芯粒+IOD芯粒。",ez:"芯片设计从大块头变小积木"},
  {rank:16,cat:'tech',term:"HBM",pro:"High Bandwidth Memory，高带宽内存，通过TSV堆叠DRAM芯片，与GPU/CPU通过2.5D封装集成。HBM3带宽可达819GB/s，用于AI芯片。",ez:"堆叠的高带宽内存"},
  {rank:17,cat:'tech',term:"硅桥",pro:"Embedded Multi-die Interconnect Bridge，嵌入封装基板的硅桥，实现芯片间高密度互连。Intel EMIB技术，线距可达55μm。",ez:"芯片间的硅制小桥"},
  {rank:18,cat:'tech',term:"扇出型封装",pro:"Fan-Out Wafer Level Packaging，将芯片嵌入模塑料，通过布线层引出I/O，无需基板。用于移动芯片，如华为麒麟990。",ez:"芯片引脚向外扇出的封装"},
  {rank:19,cat:'tech',term:"微凸块",pro:"Micro Bump，用于芯片与中介层或芯片间互连的微小焊球，直径约20-50μm，间距40-100μm，实现高密度连接。",ez:"芯片上的微小焊点"},
  {rank:20,cat:'tech',term:"混合键合",pro:"Hybrid Bonding，无焊料直接键合铜触点，间距可小于10μm，用于3D堆叠。如索尼CMOS图像传感器，实现高密度互联。",ez:"铜对铜直接压合"},
  {rank:21,cat:'tech',term:"Interposer",pro:"中介层，2.5D封装中用于承载芯片的硅或有机基板，提供高密度布线。硅中介层线宽可达0.5μm，有机中介层线宽约2μm。",ez:"芯片底下的连接板"},
  {rank:22,cat:'tech',term:"Chiplet互连",pro:"芯粒间通信技术，包括串行（如UCIe）和并行（如BoW），支持不同协议。UCIe支持PCIe/CXL等协议，速率达32GT/s。",ez:"芯粒间怎么说话"},
  {rank:23,cat:'tech',term:"BoW",pro:"Bridge of Wires，开放互连标准，由Open Compute Project推动，支持Chiplet间并行通信，功耗低，用于数据中心。",ez:"另一种芯片互连标准"},
  {rank:24,cat:'tech',term:"先进封装基板",pro:"用于2.5D/3D封装的基板，如ABF基板，线宽/线距可达8/8μm，层数可达20层，用于高性能芯片。",ez:"高级芯片底板"},
  {rank:25,cat:'tech',term:"3D IC",pro:"三维集成电路，通过3D堆叠多个芯片层，实现高集成度。典型如Intel Foveros，AMD 3D V-Cache，堆叠SRAM提升性能。",ez:"立体芯片"},
  {rank:26,cat:'biz',term:"台积电",pro:"全球最大晶圆代工厂，提供先进封装服务CoWoS/InFO，2023年先进封装营收超60亿美元，客户包括NVIDIA、AMD。",ez:"芯片代工老大，也做封装"},
  {rank:27,cat:'biz',term:"长电科技",pro:"中国最大半导体封装测试企业，提供Chiplet封装方案，拥有2.5D/3D封装能力，2023年营收约300亿元。",ez:"中国封装一哥"},
  {rank:28,cat:'biz',term:"通富微电",pro:"国内领先封装企业，与AMD深度合作，为MI300提供封装服务，拥有2.5D封装产线，2023年营收约200亿元。",ez:"AMD的封装伙伴"},
  {rank:29,cat:'biz',term:"华天科技",pro:"国内封装企业，布局Chiplet封装，掌握TSV、扇出型技术，2023年营收约120亿元，客户包括国内芯片设计公司。",ez:"国内封装老三"},
  {rank:30,cat:'biz',term:"Intel",pro:"推出Foveros 3D封装和EMIB技术，用于自家处理器，同时提供代工服务，2023年封装业务营收约20亿美元。",ez:"Intel也做封装代工"},
  {rank:31,cat:'biz',term:"AMD",pro:"Chiplet架构先驱，Zen系列CPU和MI300 GPU均采用Chiplet，通过先进封装提升性能，2023年营收约230亿美元。",ez:"Chiplet的先行者"},
  {rank:32,cat:'biz',term:"NVIDIA",pro:"AI芯片巨头，采用台积电CoWoS封装，将GPU与HBM集成，如H100，2023年营收约600亿美元。",ez:"AI芯片霸主，用CoWoS封装"},
  {rank:33,cat:'biz',term:"Chiplet设计生态",pro:"包括IP供应商（如ARM）、设计工具（如Cadence）、代工厂（台积电）、封测厂（日月光）等，推动标准化。",ez:"Chiplet的产业链"},
  {rank:34,cat:'biz',term:"开放式Chiplet",pro:"基于UCIe等开放标准，实现不同厂商Chiplet互操作，降低门槛。如英特尔、AMD、ARM等成立UCIe联盟。",ez:"不同厂家的积木能通用"},
  {rank:35,cat:'biz',term:"Chiplet IP",pro:"可复用的Chiplet设计模块，如SerDes、内存控制器，厂商可购买集成。ARM推出Chiplet架构，支持定制。",ez:"卖芯粒设计图纸"},
  {rank:36,cat:'finance',term:"先进封装市场规模",pro:"2023年约400亿美元，预计2028年达700亿美元，年复合增长率10%以上，Chiplet是主要驱动力。",ez:"先进封装市场400亿美元"},
  {rank:37,cat:'finance',term:"封装设备投资",pro:"先进封装设备（如晶圆级封装、TSV刻蚀）投资巨大，一条2.5D封装线投资约5亿美元，台积电2023年资本支出360亿美元。",ez:"封装设备很烧钱"},
  {rank:38,cat:'finance',term:"毛利率",pro:"封测企业毛利率通常20-30%，先进封装毛利率较高，如台积电封装毛利率约40%，长电科技约25%。",ez:"封装毛利率约20-40%"},
  {rank:39,cat:'finance',term:"研发投入占比",pro:"Chiplet企业研发投入高，AMD研发占比约20%，Intel约15%，台积电约8%，用于先进封装和互联技术。",ez:"研发投入占比高"},
  {rank:40,cat:'finance',term:"资本开支强度",pro:"封装企业资本开支占营收比例高，如台积电约50%，长电科技约20%，用于扩产先进封装产能。",ez:"资本开支占比高"}
];
