window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['cybersec'] = [
  {rank:1,cat:'core',term:"零信任",pro:"零信任是一种安全模型，假设网络内外均不可信，要求对每次访问进行身份验证和授权。Gartner预测到2026年，10%的大型企业将采用零信任架构。",ez:"永不信任，始终验证"},
  {rank:2,cat:'core',term:"SASE",pro:"安全访问服务边缘（SASE）将网络和安全功能融合到云交付模型中。据Gartner，到2025年80%的企业将采用SASE架构。",ez:"云上的安全网络服务"},
  {rank:3,cat:'core',term:"EDR",pro:"端点检测与响应（EDR）实时监控端点活动以检测威胁。CrowdStrike的Falcon平台覆盖超过1800万个端点。",ez:"电脑上的监控报警系统"},
  {rank:4,cat:'core',term:"XDR",pro:"扩展检测与响应（XDR）整合多个安全产品数据以提升威胁检测。Palo Alto Networks的Cortex XDR支持超过1000种集成。",ez:"打通所有安全工具"},
  {rank:5,cat:'core',term:"态势感知",pro:"网络安全态势感知通过大数据分析实时掌握网络风险。奇安信的天眼系统每天处理超过10亿条告警。",ez:"网络安全全景地图"},
  {rank:6,cat:'core',term:"渗透测试",pro:"渗透测试模拟攻击以评估系统安全性。据Synack报告，平均渗透测试发现15个高危漏洞。",ez:"模拟黑客攻击找漏洞"},
  {rank:7,cat:'core',term:"Palo Alto Networks",pro:"全球领先的网络安全公司，提供下一代防火墙和云安全。2023财年营收69亿美元，服务超过8万客户。",ez:"防火墙巨头"},
  {rank:8,cat:'core',term:"CrowdStrike",pro:"云原生端点安全领导者，Falcon平台基于AI检测威胁。2024财年营收30.6亿美元，订阅客户超2.4万。",ez:"云杀毒明星"},
  {rank:9,cat:'core',term:"奇安信",pro:"中国网络安全领军企业，专注政企安全。2023年营收64亿元，员工超1.2万人，服务90%以上中央部委。",ez:"中国网安一哥"},
  {rank:10,cat:'core',term:"深信服",pro:"中国网络安全和云计算厂商，超融合和VPN市场份额领先。2023年营收76亿元，客户超10万家。",ez:"国产安全+云"},
  {rank:11,cat:'core',term:"数据安全",pro:"保护数据免受泄露和篡改，涉及加密、DLP等。据IBM，2023年数据泄露平均成本445万美元。",ez:"保护数据不被偷"},
  {rank:12,cat:'core',term:"Web3.0安全",pro:"针对去中心化应用和区块链的安全挑战。2022年Web3安全事件损失超30亿美元，智能合约漏洞是主要风险。",ez:"区块链安全"},
  {rank:13,cat:'core',term:"防火墙",pro:"网络安全基础设备，监控和控制网络流量。Palo Alto的下一代防火墙可识别超过5000种应用。",ez:"网络大门保安"},
  {rank:14,cat:'core',term:"入侵检测系统",pro:"IDS监控网络流量以发现恶意活动。Snort是开源IDS，被超过400万用户使用。",ez:"网络入侵报警器"},
  {rank:15,cat:'core',term:"漏洞",pro:"系统缺陷可被利用进行攻击。2023年CVE数据库新增超过2万个漏洞，平均修复时间约60天。",ez:"系统里的安全洞"},
  {rank:16,cat:'tech',term:"沙箱",pro:"隔离环境运行可疑文件以分析行为。FireEye的沙箱检测率超过95%，可模拟多种操作系统。",ez:"隔离运行危险软件"},
  {rank:17,cat:'tech',term:"端点安全",pro:"保护笔记本电脑、手机等设备。CrowdStrike Falcon的AI模型每秒处理超过1万亿个特征。",ez:"保护电脑手机安全"},
  {rank:18,cat:'tech',term:"云安全",pro:"保护云基础设施和数据。据Gartner，2024年全球云安全支出超70亿美元。",ez:"云上的安全防护"},
  {rank:19,cat:'tech',term:"身份与访问管理",pro:"IAM管理用户身份和访问权限。Okta的客户超过1.7万家，每天处理超过10亿次认证。",ez:"账号权限管理"},
  {rank:20,cat:'tech',term:"安全信息与事件管理",pro:"SIEM集中收集和分析安全日志。Splunk Enterprise Security处理每天超过10TB数据。",ez:"安全日志分析中心"},
  {rank:21,cat:'tech',term:"网络流量分析",pro:"NTA监控网络流量以发现异常。Darktrace的AI模型可检测零日攻击，误报率低于0.1%。",ez:"网络流量行为分析"},
  {rank:22,cat:'tech',term:"威胁情报",pro:"收集分析威胁信息以预防攻击。Recorded Future每天处理超过200万条情报源。",ez:"黑客情报收集"},
  {rank:23,cat:'tech',term:"安全编排自动化与响应",pro:"SOAR自动化安全操作流程。Splunk Phantom可集成超过300种安全工具。",ez:"安全自动化响应"},
  {rank:24,cat:'tech',term:"数据丢失防护",pro:"DLP防止敏感数据外泄。Symantec DLP可识别超过100种数据类型。",ez:"防止数据外泄"},
  {rank:25,cat:'tech',term:"加密",pro:"将数据转换为密文保护机密性。AES-256被美国政府用于绝密级数据。",ez:"数据加密锁"},
  {rank:26,cat:'biz',term:"订阅模式",pro:"按年或月付费使用安全服务。CrowdStrike 95%收入来自订阅，2024年ARR达34.5亿美元。",ez:"租用安全软件"},
  {rank:27,cat:'biz',term:"SaaS安全",pro:"安全即服务，通过云交付安全功能。Zscaler的零信任平台服务全球超过6000家企业。",ez:"安全软件云服务"},
  {rank:28,cat:'biz',term:"MSSP",pro:"托管安全服务提供商，远程管理安全设备。Trustwave为全球超过100万客户提供MSS。",ez:"外包安全运维"},
  {rank:29,cat:'biz',term:"网络安全保险",pro:"覆盖数据泄露等损失。2023年全球网络安全保险保费超150亿美元。",ez:"黑客攻击保险"},
  {rank:30,cat:'biz',term:"合规驱动",pro:"法规如GDPR推动安全投入。GDPR违规罚款最高2000万欧元或全球营收4%。",ez:"法规逼你买安全"},
  {rank:31,cat:'biz',term:"安全运营中心",pro:"SOC集中监控和响应安全事件。IBM的SOC每天处理超过1万亿条安全事件。",ez:"网络安全指挥中心"},
  {rank:32,cat:'biz',term:"威胁狩猎",pro:"主动搜索隐藏威胁。Mandiant的威胁狩猎团队每年发现超过1000个高级威胁。",ez:"主动找黑客"},
  {rank:33,cat:'biz',term:"漏洞赏金",pro:"奖励发现漏洞的研究人员。HackerOne平台已发放超过1.2亿美元赏金。",ez:"找漏洞赚钱"},
  {rank:34,cat:'biz',term:"安全培训",pro:"提升员工安全意识。KnowBe4的培训覆盖全球超过5万客户。",ez:"员工防骗培训"},
  {rank:35,cat:'biz',term:"零日漏洞",pro:"未公开的漏洞，无补丁可用。2023年零日漏洞利用数量创纪录，超过80个。",ez:"无解的安全漏洞"},
  {rank:36,cat:'finance',term:"ARR",pro:"年度经常性收入，衡量订阅业务健康度。CrowdStrike FY2024 ARR为34.5亿美元，同比增长34%。",ez:"年订阅收入"},
  {rank:37,cat:'finance',term:"净留存率",pro:"衡量现有客户收入增长。Palo Alto Networks FY2023净留存率超120%。",ez:"老客户多花钱比例"},
  {rank:38,cat:'finance',term:"毛利率",pro:"收入减去成本后的利润率。安全软件公司毛利率通常超70%，如Zscaler毛利率约80%。",ez:"毛利空间"},
  {rank:39,cat:'finance',term:"客户获取成本",pro:"获取一个新客户的平均成本。SaaS安全公司CAC通常在数千美元。",ez:"拉新成本"},
  {rank:40,cat:'finance',term:"总可寻址市场",pro:"产品或服务的潜在市场规模。据Gartner，2024年全球网络安全TAM超2000亿美元。",ez:"市场蛋糕大小"}
];
