window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['digitalTwin'] = [
  {rank:1,cat:'core',term:"数字孪生",pro:"数字孪生是通过物理模型、传感器数据等构建的虚拟映射，实现全生命周期实时同步。据Gartner预测，到2025年超半数大型企业将采用。",ez:"物理世界的数字镜像"},
  {rank:2,cat:'core',term:"物理模型",pro:"基于物理定律的数学描述，用于模拟实体行为。ANSYS等工具可构建高保真模型，精度达99%以上。",ez:"模拟真实世界的数学公式"},
  {rank:3,cat:'core',term:"实时数据同步",pro:"通过IoT传感器每秒采集数千数据点，实现虚拟模型与物理实体的毫秒级同步。西门子MindSphere支持百万级设备并发。",ez:"虚拟和现实数据随时同步"},
  {rank:4,cat:'core',term:"仿真建模",pro:"利用3D建模和仿真引擎（如Unity）创建数字副本，可进行虚拟测试。达索系统3DEXPERIENCE平台支持多物理场耦合仿真。",ez:"建个虚拟模型来模拟测试"},
  {rank:5,cat:'core',term:"生命周期管理",pro:"覆���设计、制造、运维到退役的全过程，通过数字孪生可降低产品开发成本30%。西门子NX软件支持端到端管理。",ez:"从生到死的全程管理"},
  {rank:6,cat:'core',term:"智慧城市孪生",pro:"城市级数字孪生整合交通、能源等系统，新加坡虚拟新加坡项目可模拟300万人口流动，优化应急响应。",ez:"城市的数字双胞胎"},
  {rank:7,cat:'core',term:"数字工厂",pro:"工厂的数字孪生实现生产流程仿真，GE Predix平台可预测设备故障，减少停机时间20%。",ez:"工厂的虚拟副本"},
  {rank:8,cat:'core',term:"BIM",pro:"建筑信息模型，集成几何与属性数据。Autodesk Revit支持多专业协同，可减少施工返工15%。",ez:"建筑的3D信息模型"},
  {rank:9,cat:'core',term:"元宇宙基建",pro:"数字孪生是元宇宙的基石，英伟达Omniverse可连接多软件，实现实时协作，已用于宝马工厂。",ez:"元宇宙的底层基础设施"},
  {rank:10,cat:'core',term:"数字线程",pro:"连接不同阶段数据的闭环，确保信息一致性。波音利用数字线程将777X开发周期缩短30%。",ez:"数据贯穿产品全生命周期"},
  {rank:11,cat:'core',term:"数字孪生体",pro:"物理实体的虚拟代表，具备自我演化能力。Gartner定义其需包含模型、数据、唯一标识。",ez:"实体的数字替身"},
  {rank:12,cat:'core',term:"虚实映射",pro:"物理与虚拟空间的双向映射，实现控制与反馈。微软Azure Digital Twins支持实时双向同步。",ez:"现实和虚拟互相影响"},
  {rank:13,cat:'core',term:"预测性维护",pro:"通过分析孪生数据预测故障，GE航空的预测维护可降低维修成本25%，每年避免数百次航班延误。",ez:"提前知道设备要坏"},
  {rank:14,cat:'core',term:"数字孪生平台",pro:"集成建模、仿真、分析的一体化平台。西门子Xcelerator连接IT与OT，已服务超10万客户。",ez:"做数字孪生的一站式工具"},
  {rank:15,cat:'core',term:"数字孪生标准",pro:"ISO 23247系列标准定义了数字孪生框架，促进互操作性。中国也已发布《数字孪生应用白皮书》。",ez:"数字孪生的统一规范"},
  {rank:16,cat:'tech',term:"IoT传���器",pro:"采集物理数据的关键设备，全球IoT设备2023年超150亿台，每秒产生PB级数据。",ez:"万物互联的感知器"},
  {rank:17,cat:'tech',term:"数字孪生引擎",pro:"如Unity、Unreal Engine，支持实时3D渲染与物理模拟。Unity数字孪生方案已用于自动驾驶仿真。",ez:"制作数字孪生的游戏引擎"},
  {rank:18,cat:'tech',term:"多物理场仿真",pro:"同时模拟热、力、电磁等物理场。ANSYS Twin Builder支持耦合分析，精度提升40%。",ez:"多种物理现象一起模拟"},
  {rank:19,cat:'tech',term:"数据融合",pro:"整合多源异构数据，如CAD、BIM、IoT数据。达索系统通过数据融合实现模型一致性达95%。",ez:"把不同数据合在一起"},
  {rank:20,cat:'tech',term:"云计算",pro:"提供算力支持，AWS IoT TwinMaker可快速构建孪生，降低基础设施成本50%。",ez:"用云上的电脑处理数据"},
  {rank:21,cat:'tech',term:"边缘计算",pro:"在靠近数据源处处理，减少延迟。西门子Industrial Edge可本地分析，响应时间<10ms。",ez:"在设备旁边算数据"},
  {rank:22,cat:'tech',term:"AI/ML",pro:"用于预测与优化，如用LSTM预测设备寿命。GE Predix利用ML模型准确率达90%以上。",ez:"人工智能分析数据"},
  {rank:23,cat:'tech',term:"数字孪生API",pro:"开放接口便于集成，微软Azure Digital Twins API支持RESTful调用，每秒处理万级请求。",ez:"数字孪生的程序接口"},
  {rank:24,cat:'tech',term:"数字孪生安全",pro:"保障数据与模型安全，需加密与访问控制。工业数字孪生安全标准IEC 62443已应用。",ez:"防止数字孪生被黑"},
  {rank:25,cat:'tech',term:"数字孪生互操作",pro:"不同系统间数据交换，如通过OPC UA协议。西门子与SAP合作实现ERP与MES互操作。",ez:"不同软件能互相通信"},
  {rank:26,cat:'biz',term:"GE Predix",pro:"工业互联网平台，用于资产性能管理。GE曾投资数十亿美元，虽转型但仍是数字孪生先驱。",ez:"GE的工业云平台"},
  {rank:27,cat:'biz',term:"Siemens Xcelerator",pro:"集成软硬件与服务，连接数字孪生全生命周期。已帮助客户缩短产品上市时间30%。",ez:"西门子的数字孪生全家桶"},
  {rank:28,cat:'biz',term:"ANSYS Twin Builder",pro:"系统级数字孪生仿真工具，支持模型降阶。用于航空航天，可减少物理测试50%。",ez:"ANSYS的孪生仿真软件"},
  {rank:29,cat:'biz',term:"达索系统3DEXPERIENCE",pro:"协同平台，整合设计、仿真、制造。空客使用后，飞机设计周期缩短25%。",ez:"达索的3D协作平台"},
  {rank:30,cat:'biz',term:"Azure Digital Twins",pro:"微软云数字孪生服务，支持创建大规模模型。已用于智能建筑，能耗降低20%。",ez:"微软的云上孪生服务"},
  {rank:31,cat:'biz',term:"AWS IoT TwinMaker",pro:"亚马逊数字孪生服务，快速构建工业孪生。用户可集成现有数据，成本降低40%。",ez:"亚马逊的工业孪生工具"},
  {rank:32,cat:'biz',term:"NVIDIA Omniverse",pro:"用于协作与仿真，支持实时光线追踪。宝马使用后，规划效率提升30%。",ez:"英伟达的元宇宙协作平台"},
  {rank:33,cat:'biz',term:"数字孪生咨询",pro:"如埃森哲、德勤提供战略与实施服务，市场年增长率超30%。",ez:"帮你做数字孪生的顾问"},
  {rank:34,cat:'biz',term:"数字孪生SaaS",pro:"按需付费模式，如Bentley iTwin，降低中小企业门槛，订阅用户年增50%。",ez:"租用数字孪生软件"},
  {rank:35,cat:'biz',term:"数字孪生开源",pro:"如Eclipse Ditto，提供开放框架，社区贡献者超500人。",ez:"免费的数字孪生代码"},
  {rank:36,cat:'finance',term:"数字孪生市场规模",pro:"据MarketsandMarkets，2023年全球市场约89亿美元，预计2028年达259亿美元，CAGR 23.8%。",ez:"数字孪生市场有多大"},
  {rank:37,cat:'finance',term:"投资回报率ROI",pro:"典型数字孪生项目ROI可达300%，如预测维护减少停机，每年节省数百万美元。",ez:"投钱做孪生能赚多少"},
  {rank:38,cat:'finance',term:"总拥有成本TCO",pro:"包括软件、硬件、实施与运维。大型企业TCO约500万美元，但5年可回收。",ez:"做数字孪生总共花多少钱"},
  {rank:39,cat:'finance',term:"资本支出CAPEX",pro:"初期投入，如购买传感器、服务器。典型工厂CAPEX约200万元，占项目成本60%。",ez:"买硬件的一次性投入"},
  {rank:40,cat:'finance',term:"运营支出OPEX",pro:"持续费用，如云服务、维护。云模式OPEX可降低30%，按需付费。",ez:"每年要花的维护费"}
];
