window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['erp'] = [
  {rank:1,cat:'core',term:"ERP",pro:"企业资源计划系统，整合财务、供应链、生产等核心业务流程。全球ERP市场2023年规模超500亿美元。",ez:"公司管理软件全家桶"},
  {rank:2,cat:'core',term:"SAP S/4HANA",pro:"SAP第四代ERP套件，基于内存计算平台HANA，支持实时分析与云部署。全球超过2万家企业使用。",ez:"SAP最新版ERP系统"},
  {rank:3,cat:'core',term:"Oracle ERP Cloud",pro:"Oracle云ERP产品，覆盖财务、采购、项目等模块，采用微服务架构。全球客户超6000家。",ez:"甲骨文云ERP"},
  {rank:4,cat:'core',term:"Workday",pro:"云端HR和财务管理系统，以SaaS模式交付，全球员工数超过1.5万。典型客户包括Netflix。",ez:"云端HR财务软件"},
  {rank:5,cat:'core',term:"金蝶K3",pro:"金蝶面向中小企业的ERP软件，涵盖财务、供应链、生产制造。在中国拥有超过80万客户。",ez:"金蝶中小企业ERP"},
  {rank:6,cat:'core',term:"用友U8",pro:"用友面向中型企业的ERP产品，支持多组织、多工厂管理。累计客户超过100万家。",ez:"用友中型企业ERP"},
  {rank:7,cat:'core',term:"Cloud ERP",pro:"基于云计算的ERP系统，按订阅付费，典型代表如NetSuite。2023年全球云ERP市场占比超40%。",ez:"云上ERP软件"},
  {rank:8,cat:'core',term:"财务云",pro:"云化的财务管理解决方案，包括总账、应收应付等。用友财务云服务超过200万家企业。",ez:"云端财务系统"},
  {rank:9,cat:'core',term:"HR云",pro:"云端人力资源管理平台，涵盖招聘、薪酬、绩效。Workday HR云全球用户超5000万。",ez:"云端人事系统"},
  {rank:10,cat:'core',term:"供应链",pro:"ERP中管理采购、库存、物流的模块。优化供应链可降低15%-30%运营成本。",ez:"公司进货发货管理"},
  {rank:11,cat:'core',term:"SaaS化ERP",pro:"以软件即服务模式交付的ERP，无需本地部署。2024年SaaS ERP市场增速超20%。",ez:"租用式ERP软件"},
  {rank:12,cat:'core',term:"MRP",pro:"物料需求计划，ERP核心功能，计算生产所需物料数量和时间。可减少库存积压30%。",ez:"算料系统"},
  {rank:13,cat:'core',term:"CRM",pro:"客户关系管理，常与ERP集成。全球CRM市场2023年超700亿美元。",ez:"客户管理软件"},
  {rank:14,cat:'core',term:"SCM",pro:"供应链管理，ERP延伸模块。有效SCM可提升交付准时率20%。",ez:"供应链管理"},
  {rank:15,cat:'core',term:"PLM",pro:"产品生命周期管理，与ERP集成管理产品数据。可缩短产品上市时间25%。",ez:"产品全流程管理"},
  {rank:16,cat:'tech',term:"SAP HANA",pro:"SAP内存计算平台，支持实时分析。S/4HANA基于此，处理速度比传统数据库快1000倍。",ez:"SAP高速数据库"},
  {rank:17,cat:'tech',term:"微服务架构",pro:"ERP云化技术，将应用拆分为独立服务。Oracle ERP Cloud采用此架构，提升扩展性。",ez:"模块化软件设计"},
  {rank:18,cat:'tech',term:"API集成",pro:"ERP与其他系统通过API连接。Workday提供超过500个REST API。",ez:"软件接口对接"},
  {rank:19,cat:'tech',term:"人工智能",pro:"ERP中AI用于预测分析、自动化。SAP AI可预测供应链中断，准确率超85%。",ez:"ERP智能助手"},
  {rank:20,cat:'tech',term:"机器人流程自动化",pro:"RPA自动执行ERP重复任务。用友RPA可减少财务对账人力80%。",ez:"软件机器人干活"},
  {rank:21,cat:'tech',term:"区块链",pro:"用于ERP供应链溯源。IBM与SAP合作，将区块链集成至ERP。",ez:"防篡改记录技术"},
  {rank:22,cat:'tech',term:"物联网",pro:"IoT设备数据接入ERP，实现实时监控。金蝶云星空支持IoT设备集成。",ez:"设备联网进ERP"},
  {rank:23,cat:'tech',term:"低代码平台",pro:"快速定制ERP功能。SAP Business Technology Platform支持低代码开发。",ez:"拖拽式开发工具"},
  {rank:24,cat:'tech',term:"数据仓库",pro:"ERP数据分析基础。Oracle Autonomous Data Warehouse与ERP集成。",ez:"ERP数据仓库"},
  {rank:25,cat:'tech',term:"云原生",pro:"ERP系统专为云设计。Workday是云原生ERP代表，100% SaaS。",ez:"天生为云而生"},
  {rank:26,cat:'biz',term:"SaaS订阅",pro:"按年/月付费使用ERP。Salesforce ERP订阅收入年增25%。",ez:"租用软件模式"},
  {rank:27,cat:'biz',term:"按需付费",pro:"根据使用量付费的ERP模式。Oracle NetSuite提供按用户付费。",ez:"用多少付多少"},
  {rank:28,cat:'biz',term:"私有云部署",pro:"ERP部署在客户专属云环境。SAP S/4HANA私有云版本满足大企业安全需求。",ez:"专属云上ERP"},
  {rank:29,cat:'biz',term:"混合云",pro:"部分模块公有云，部分本地。用友YonSuite支持混合云部署。",ez:"公有云+私有云混用"},
  {rank:30,cat:'biz',term:"行业解决方案",pro:"针对特定行业的ERP预配置。SAP有25个行业解决方案，如零售、制造。",ez:"行业专用ERP"},
  {rank:31,cat:'biz',term:"ERP实施",pro:"ERP部署全过程，平均周期6-18个月。失败率约30%，需专业咨询。",ez:"装ERP项目"},
  {rank:32,cat:'biz',term:"数字化转型",pro:"企业通过ERP实现业务数字化。全球数字化转型支出2025年达2.8万亿美元。",ez:"公司数字化升级"},
  {rank:33,cat:'biz',term:"业务流程重组",pro:"ERP实施前优化流程。BPR可提升效率30%以上。",ez:"流程大改造"},
  {rank:34,cat:'biz',term:"多组织管理",pro:"ERP支持多个公司或工厂。用友U8+支持多组织协同。",ez:"管多个公司"},
  {rank:35,cat:'biz',term:"全球化支持",pro:"ERP多语言、多币种、多法规。SAP支持190个国家本地化。",ez:"全球通用ERP"},
  {rank:36,cat:'finance',term:"总账",pro:"ERP财务核心模块，记录所有交易。SAP总账支持平行会计。",ez:"公司大账本"},
  {rank:37,cat:'finance',term:"应收应付",pro:"管理客户和供应商款项。自动化可减少逾期账款20%。",ez:"收钱付钱管理"},
  {rank:38,cat:'finance',term:"固定资产管理",pro:"ERP跟踪资产折旧。用友U8支持多种折旧方法。",ez:"管公司设备"},
  {rank:39,cat:'finance',term:"成本核算",pro:"计算产品成本。SAP物料账可精确到批次成本。",ez:"算成本"},
  {rank:40,cat:'finance',term:"财务报表",pro:"生成利润表、资产负债表。Oracle ERP Cloud实时报表。",ez:"出财报"}
];
