window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['embodied_ai'] = [
  {rank:1,cat:'core',term:"具身智能",pro:"指能够感知环境、自主决策并执行物理动作的智能体，如人形机器人。2024年全球市场规模约20亿美元。",ez:"有身体的AI"},
  {rank:2,cat:'core',term:"人形机器人",pro:"模仿人类形态和运动的机器人，典型如特斯拉Optimus、波士顿动力Atlas。2025年预计量产千台。",ez:"长得像人的机器人"},
  {rank:3,cat:'core',term:"VLA模型",pro:"视觉-语言-动作多模态大模型，如Google RT-2，通过自然语言指令直接控制机器人。2023年首次实现零样本泛化。",ez:"看听说做一体模型"},
  {rank:4,cat:'core',term:"端到端",pro:"从传感器输入直接到电机输出的神经网络控制，如Figure AI的Helix系统。2024年实现复杂抓取任务。",ez:"输入到输出一条龙"},
  {rank:5,cat:'core',term:"仿真训练",pro:"在虚拟环境中训练机器人策略，如NVIDIA Isaac Sim。可加速1000倍，2024年宇树用其训练四足机器人。",ez:"虚拟练手"},
  {rank:6,cat:'core',term:"Sim-to-Real",pro:"将仿真环境训练的策略迁移到真实机器人，常用域随机化技术。2023年Atlas实现仿真到现实的跳跃动作。",ez:"虚拟到现实"},
  {rank:7,cat:'core',term:"强化学习",pro:"通过试错和奖励函数训练机器人行为，如OpenAI训练机械手解魔方。2024年用于宇树H1后空翻。",ez:"奖励驱动学习"},
  {rank:8,cat:'core',term:"遥操作",pro:"人类远程控制机器人执行任务，如特斯拉Optimus的远程演示。2024年Figure 01通过遥操作学习煮咖啡。",ez:"远程操控"},
  {rank:9,cat:'core',term:"灵巧手",pro:"高自由度仿人机械手，如Shadow Robot的DexHand。2024年1X Neo配备14自由度灵巧手。",ez:"灵活机器手"},
  {rank:10,cat:'core',term:"运动控制",pro:"控制机器人关节实现稳定行走、奔跑等，如波士顿动力Atlas的模型预测控制。2024年实现跑酷。",ez:"走路跑步控制"},
  {rank:11,cat:'core',term:"感知融合",pro:"融合摄像头、激光雷达、触觉等多传感器数据，如特斯拉Optimus的纯视觉方案。2024年实现毫米级定位。",ez:"多感��合并"},
  {rank:12,cat:'core',term:"自主导航",pro:"机器人在未知环境中自主规划路径并避障，如宇树H1的SLAM技术。2024年实现动态避障。",ez:"自己找路走"},
  {rank:13,cat:'core',term:"任务规划",pro:"将复杂任务分解为子步骤并排序，如Google RT-X的链式思维规划。2024年完成长序列任务。",ez:"分步做任务"},
  {rank:14,cat:'core',term:"人机交互",pro:"通过语音、手势等方式与机器人交流，如Figure 01的对话能力。2024年实现自然语言指令理解。",ez:"和机器人聊天"},
  {rank:15,cat:'core',term:"安全机制",pro:"防止机器人伤人/自毁的软硬件设计，如力控关节和急停按钮。2024年ISO 13482标准更新。",ez:"防撞防摔"},
  {rank:16,cat:'tech',term:"RT-X",pro:"Google和伯克利合作的开源机器人数据集，含22种机器人、500+任务。2023年发布，推动跨平台泛化。",ez:"机器人训练数据集"},
  {rank:17,cat:'tech',term:"RoboSuite",pro:"基于MuJoCo的机器人仿真环境，支持Franka、KUKA等。2024年用于多任务强化学习基准。",ez:"机器人模拟器"},
  {rank:18,cat:'tech',term:"模型预测控制",pro:"基于动力学模型预测未来状态并优化控制量，如Atlas的MPC控制器。2024年实现每秒1000次优化。",ez:"预测式控制"},
  {rank:19,cat:'tech',term:"逆运动学",pro:"根据末端位置反算关节角度，如机械臂抓取。2024年宇树H1使用IK实现精准步态。",ez:"反算关节角度"},
  {rank:20,cat:'tech',term:"力控",pro:"通过力矩传感器实现柔顺控制，如协作机器人。2024年Figure 01力控精度达0.1N。",ez:"感知力度控制"},
  {rank:21,cat:'tech',term:"触觉传感器",pro:"模拟人类触觉的电子皮肤，如SynTouch BioTac。2024年分辨率达1mm。",ez:"电子皮肤"},
  {rank:22,cat:'tech',term:"SLAM",pro:"同时定位与地图构建，用于未知环境导航。2024年宇树H1实现室内外无缝切换。",ez:"边走路边画地图"},
  {rank:23,cat:'tech',term:"域随机化",pro:"在仿真中随机化物理参数以增强Sim-to-Real迁移。2023年OpenAI用其训练Dactyl手。",ez:"虚拟随机化训练"},
  {rank:24,cat:'tech',term:"模仿学习",pro:"通过人类演示数据学习策略，如1X Neo的遥操作数据。2024年实现煮咖啡等家务。",ez:"看人学动作"},
  {rank:25,cat:'tech',term:"行为克隆",pro:"直接复制人类动作的监督学习方法，如RT-2。2024年成功率提升至80%。",ez:"复制人类动作"},
  {rank:26,cat:'biz',term:"特斯拉Optimus",pro:"特斯拉开发的人形机器人，目标售价2万美元。2024年已开始在工厂搬运电池。",ez:"特斯拉机器人"},
  {rank:27,cat:'biz',term:"波士顿动力Atlas",pro:"最先进的人形机器人之一，采用液压驱动。2024年展示跑酷和空翻，未商业化。",ez:"会翻跟头的机器人"},
  {rank:28,cat:'biz',term:"Figure AI",pro:"开发通用人形机器人的初创公司，获微软、OpenAI投资。2024年Figure 01展示自主煮咖啡。",ez:"Figure机器人公司"},
  {rank:29,cat:'biz',term:"宇树科技",pro:"中国四足/人形机器人公司，H1人形机器人售价9.9万元。2024年实现后空翻。",ez:"中国宇树机器人"},
  {rank:30,cat:'biz',term:"1X Neo",pro:"挪威公司1X Technologies的人形机器人，用于家庭服务。2024年获得OpenAI投资。",ez:"1X家庭机器人"},
  {rank:31,cat:'biz',term:"Agility Digit",pro:"专注物流的人形机器人，已与福特合作。2024年部署于仓库搬运包裹。",ez:"物流人形机器人"},
  {rank:32,cat:'biz',term:"协作机器人",pro:"可与人类安全共事的机器人，如UR5e。2024年全球销量超5万台。",ez:"和人一起干活的机器人"},
  {rank:33,cat:'biz',term:"机器人即服务",pro:"按需租赁机器人，降低客户门槛。2024年RaaS市场达50亿美元。",ez:"租机器人用"},
  {rank:34,cat:'biz',term:"具身智能芯片",pro:"专为机器人设计的AI芯片，如NVIDIA Jetson。2024年Orin算力达275TOPS。",ez:"机器人专用芯片"},
  {rank:35,cat:'biz',term:"开源机器人",pro:"开源硬件和软件平台，如ROS 2和Unitree SDK。2024年社区贡献者超10万。",ez:"开源机器人平台"},
  {rank:36,cat:'finance',term:"机器人单价",pro:"人形机器人平均售价约10万美元，Optimus目标2万美元。2024年宇树H1售价9.9万元。",ez:"机器人卖多少钱"},
  {rank:37,cat:'finance',term:"研发投入占比",pro:"头部企业研发费用占营收30-50%，如波士顿动力每年烧钱1亿美元。2024年Figure AI融资6.75亿美元。",ez:"研发花多少钱"},
  {rank:38,cat:'finance',term:"总拥有成本",pro:"机器人全生命周期成本，包括采购、维护、能耗。2024年Digit的TCO约5美元/小时。",ez:"机器人总成本"},
  {rank:39,cat:'finance',term:"投资回报期",pro:"机器人替代人工的回本时间，制造业通常1-3年。2024年Optimus预计回本2年。",ez:"多久回本"},
  {rank:40,cat:'finance',term:"市场规模",pro:"人形机器人市场2030年预计达380亿美元，2024年约20亿美元。",ez:"市场有多大"}
];
