/* IndustryLens — 林业碳汇 关键词百科 */
KEYWORDS_DB['forestry'] = [
{rank:1,cat:'biz',term:"造纸",pro:"晨鸣纸业/太阳纸业/博汇。木浆驱动。",ez:"做纸的。"},
{rank:2,cat:'biz',term:"林浆纸一体化",pro:"种林→制浆→造纸。成本可控。",ez:"树到纸一条龙。"},
{rank:3,cat:'biz',term:"木材",pro:"进口为主。俄罗斯/东南亚。",ez:"木头。"},
{rank:4,cat:'biz',term:"竹制品",pro:"竹地板/竹家具/竹纤维。可再生低碳。",ez:"竹子做的东西。"},
{rank:5,cat:'core',term:"林业碳汇",pro:"按吨碳计价。国家林业碳汇交易试点。",ez:"树吸碳也能卖钱。"},
{rank:6,cat:'biz',term:"CCER林业",pro:"2024年方法学重启。林业碳汇主力。",ez:"林业减排认证。"},
{rank:7,cat:'biz',term:"特种纸",pro:"仙鹤/五洲特纸。包装/食品级。",ez:"特殊用途的纸。"},
{rank:8,cat:'biz',term:"包装纸",pro:"瓦楞纸/白卡纸。电商快递推动。",ez:"包装用的纸。"},
{rank:9,cat:'biz',term:"生活用纸",pro:"心相印/洁柔。渠道下沉。",ez:"卫生纸抽纸。"},
{rank:10,cat:'biz',term:"文化纸",pro:"教材/办公用纸。数字化冲击。",ez:"书本用的纸。"},
{rank:11,cat:'core',term:"木浆",pro:"阔叶浆/针叶浆。依赖进口。",ez:"做纸的原料。"},
{rank:12,cat:'biz',term:"废纸回收",pro:"国内废纸+进口废纸。2021年禁止进口。",ez:"旧纸回收。"},
{rank:13,cat:'core',term:"森林认证",pro:"FSC认证。出口欧美门槛。",ez:"可持续森林认证。"},
{rank:14,cat:'biz',term:"家具出口",pro:"顾家家居/梦百合。东南亚替代中国。",ez:"家具出国。"},
{rank:15,cat:'biz',term:"林下经济",pro:"林菌/林药/林禽。林地综合利用。",ez:"森林里搞多种经营。"},
{rank:16,cat:'biz',term:"人造林",pro:"桉树/杨树。速生林。",ez:"人工种的快速长的林。"},
{rank:17,cat:'core',term:"天然林保护",pro:"2017年全面停伐天然林。供给受限。",ez:"国家保护天然林。"},
{rank:18,cat:'biz',term:"木结构建筑",pro:"日本/北美主流。低碳建筑方向。",ez:"木头做的房子。"},
{rank:19,cat:'finance',term:"进口木材",pro:"非洲/俄罗斯/东南亚。政策敏感。",ez:"外国进口的木头。"},
{rank:20,cat:'finance',term:"纸价周期",pro:"木浆价+需求双驱动。3-5年一轮。",ez:"纸价的涨跌。"},
];