window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['lowCode'] = [
  {rank:1,cat:'core',term:"低代码平台",pro:"低代码平台通过可视化拖拽和模型驱动，减少手写代码量，使开发者能快速构建应用。Gartner预测到2025年70%的新应用将使用低代码技术。",ez:"少写代码，快速做应用"},
  {rank:2,cat:'core',term:"零代码",pro:"零代码是低代码的极端形式，无需任何编程即可通过配置完成应用开发，典型产品如简道云、明道云。2023年零代码市场规模超50亿元。",ez:"完全不用写代码"},
  {rank:3,cat:'core',term:"可视化开发",pro:"可视化开发通过图形界面拖拽组件、配置属性来构建应用，降低开发门槛。OutSystems和Mendix均以此为核心。",ez:"像搭积木一样做软件"},
  {rank:4,cat:'core',term:"模型驱动开发",pro:"模型驱动开发以数据模型、业务逻辑模型为核心，自动生成代码和界面。Mendix的微流（Microflow）即模型驱动示例。",ez:"先画模型，自动生成"},
  {rank:5,cat:'core',term:"业务流程管理",pro:"BPM通过低代码平台实现流程设计、执行、监控和优化，如钉钉宜搭的流程表单。全球BPM市场2023年达120亿美元。",ez:"把业务流程搬到线上"},
  {rank:6,cat:'core',term:"快速应用开发",pro:"RAD强调快速迭代和原型设计，低代码平台将RAD理念产品化，缩短交付周期。OutSystems声称可提升开发效率10倍。",ez:"快速出应用，边用边改"},
  {rank:7,cat:'core',term:"企业级低代码",pro:"企业级低代码平台支持复杂业务、高并发、安全合规，如OutSystems和Mendix。2023年企业级低代码市场占整体60%以上。",ez:"给大公司用的低代码"},
  {rank:8,cat:'core',term:"公民开发者",pro:"公民开发者指非IT专业人员利用低代码平台创建应用，Gartner预测到2026年公民开发者将占低代码用户80%。",ez:"业务人员自己开发"},
  {rank:9,cat:'core',term:"低代码PaaS",pro:"低代码PaaS提供开发、部署、运维一体化平台，如Mendix Cloud和OutSystems Cloud。典型客户包括宝马、大众等。",ez:"开发平台即服务"},
  {rank:10,cat:'core',term:"表单驱动",pro:"表单驱动通过设计表单来定义数据结构和业务逻辑，常见于简道云、明道云。用户可快速创建数据收集和管理应用。",ez:"填表单就能做应用"},
  {rank:11,cat:'core',term:"事件驱动架构",pro:"事件驱动架构通过事件触发业务逻辑，低代码平台如Mendix支持事件驱动微流。适用于实时响应场景。",ez:"发生事情就自动执行"},
  {rank:12,cat:'core',term:"微服务架构",pro:"低代码平台常基于微服务架构，支持独立部署和扩展。OutSystems采用微服务设计，服务间通过API通信。",ez:"拆成小服务，独立部署"},
  {rank:13,cat:'core',term:"API集成",pro:"低代码平台通过预置连接器或自定义API集成外部系统，如Salesforce、SAP。钉钉宜搭支持200+API连接。",ez:"连接其他系统"},
  {rank:14,cat:'core',term:"多租户架构",pro:"多租户架构使一个实例服务多个客户，数据隔离。低代码SaaS平台如简道云均采用此架构，降低运维成本。",ez:"一套系统给多家用"},
  {rank:15,cat:'core',term:"组件库",pro:"组件库包含预构建的UI组件、逻辑组件，开发者可拖拽复用。OutSystems提供Forge社区组件库，有5000+组件。",ez:"现成的积木块"},
  {rank:16,cat:'tech',term:"可视化编辑器",pro:"可视化编辑器提供拖拽式界面设计，支持所见即所得。Mendix的Studio Pro即专业可视化编辑器。",ez:"拖拽设计界面"},
  {rank:17,cat:'tech',term:"元数据驱动",pro:"元数据驱动将应用配置存储为元数据，运行时解析执行。低代码平台如Mendix核心引擎基于元数据。",ez:"用配置数据描述应用"},
  {rank:18,cat:'tech',term:"模型驱动架构",pro:"MDA是OMG标准，低代码平台如Mendix遵循MDA，通过平台无关模型生成平台特定代码。",ez:"模型自动转代码"},
  {rank:19,cat:'tech',term:"业务规则引擎",pro:"业务规则引擎允许用户定义条件逻辑，如折扣计算。OutSystems内置规则引擎，支持可视化配置。",ez:"设定业务规则自动执行"},
  {rank:20,cat:'tech',term:"工作流引擎",pro:"工作流引擎驱动流程流转，支持审批、任务分配。钉钉宜搭的工作流引擎支持并行、会签等模式。",ez:"自动流转审批任务"},
  {rank:21,cat:'tech',term:"前端渲染引擎",pro:"前端渲染引擎将元数据解析为UI界面，支持响应式。Mendix的Nanoflow客户端即轻量渲染引擎。",ez:"把配置变成界面"},
  {rank:22,cat:'tech',term:"后端代码生成",pro:"后端代码生成根据模型自动生成服务端代码，如REST API。OutSystems可生成C#或Java代码。",ez:"自动写后台代码"},
  {rank:23,cat:'tech',term:"连接器",pro:"连接器封装第三方系统API，简化集成。Salesforce的MuleSoft提供数百个预构建连接器。",ez:"插头一样连接系统"},
  {rank:24,cat:'tech',term:"沙箱环境",pro:"沙箱环境提供隔离的测试空间，不影响生产。低代码平台如Mendix提供个人沙箱和团队沙箱。",ez:"安全测试环境"},
  {rank:25,cat:'tech',term:"版本控制",pro:"低代码平台内置版本控制，支持回滚和分支。OutSystems的LifeTime管理应用版本和部署。",ez:"管理应用版本"},
  {rank:26,cat:'biz',term:"订阅制",pro:"低代码平台多采用SaaS订阅模式，按用户或应用收费。简道云标准版每用户年费约300元。",ez:"按年或月付费"},
  {rank:27,cat:'biz',term:"免费增值模式",pro:"免费增值模式提供基础功能免费，高级功能付费。钉钉宜搭免费版支持10个应用，付费版解锁更多。",ez:"基础免费，升级收费"},
  {rank:28,cat:'biz',term:"私有化部署",pro:"私有化部署将平台部署在客户本地服务器，满足数据安全需求。明道云支持私有化，价格按服务器规模。",ez:"装在自己服务器上"},
  {rank:29,cat:'biz',term:"应用市场",pro:"应用市场提供预构建应用模板，用户可直接安装使用。OutSystems Forge有5000+应用组件和模板。",ez:"应用商店"},
  {rank:30,cat:'biz',term:"合作伙伴生态",pro:"低代码厂商通过合作伙伴提供实施、培训等服务。Mendix全球有500+合作伙伴，覆盖行业解决方案。",ez:"合作伙伴一起卖"},
  {rank:31,cat:'biz',term:"垂直行业方案",pro:"针对特定行业提供预配置方案，如制造业MES、金融合规。OutSystems有银行、保险等行业加速器。",ez:"针对某个行业的方案"},
  {rank:32,cat:'biz',term:"低代码+AI",pro:"低代码平台集成AI能力，如智能表单、流程预测。Mendix的AI辅助开发可推荐组件。",ez:"低代码加人工智能"},
  {rank:33,cat:'biz',term:"超级自动化",pro:"超级自动化结合低代码、RPA、AI，实现端���端���动化。Gartner将低代码列为超级自动化关键技术。",ez:"自动化一切"},
  {rank:34,cat:'biz',term:"DevOps集成",pro:"低代码平台与DevOps工具链集成，支持CI/CD。OutSystems提供LifeTime管理部署流水线。",ez:"开发运维一体化"},
  {rank:35,cat:'biz',term:"低代码中台",pro:"低代码中台作为企业数字化中台，统一技术能力。阿里云宜搭作为中台支撑钉钉生态应用开发。",ez:"企业技术中台"},
  {rank:36,cat:'finance',term:"ARR",pro:"年度经常性收入，衡量SaaS业务健康度。OutSystems 2023年ARR超3亿美元，同比增长30%。",ez:"每年稳定收入"},
  {rank:37,cat:'finance',term:"MRR",pro:"月度经常性收入，追踪订阅收入变化。低代码SaaS公司通常关注MRR增长率和流失率。",ez:"每月稳定收入"},
  {rank:38,cat:'finance',term:"客户生命周期价值",pro:"LTV指客户在整个生命周期内贡献的总收入。低代码平台LTV通常较高，因粘性强。",ez:"客户总价值"},
  {rank:39,cat:'finance',term:"客户获取成本",pro:"CAC指获取一个新客户的平均成本。低代码厂商CAC较高，因需要销售和POC。",ez:"拉新成本"},
  {rank:40,cat:'finance',term:"净收入留存率",pro:"NRR衡量现有客户收入增长，包括增购和流失。优秀低代码公司NRR通常超过120%。",ez:"老客户续费增购率"}
];
