window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['luxury'] = [
  {rank:1,cat:'core',term:"奢侈品",pro:"奢侈品指价格高昂、品质卓越、设计独特且品牌价值高的商品，如LV、Hermès等，全球市场2023年规模约1.5万亿欧元。",ez:"贵且好的东西"},
  {rank:2,cat:'core',term:"品牌溢价",pro:"品牌溢价指消费者为品牌名称支付的额外费用，通常占奢侈品价格的50%-80%，如Chanel经典款手袋成本仅占售价的10%。",ez:"为牌子多付钱"},
  {rank:3,cat:'core',term:"稀缺性",pro:"稀缺性指通过限量生产或独家分销提升产品价值，如Hermès Birkin包年产量仅约5万只，需排队数年。",ez:"物以稀为贵"},
  {rank:4,cat:'core',term:"LVMH",pro:"全球最大奢侈品集团，旗下拥有Louis Vuitton、Dior、Tiffany等75个品牌，2023年营收862亿欧元，市值超4000亿欧元。",ez:"奢侈品界的航母"},
  {rank:5,cat:'core',term:"Hermès爱马仕",pro:"法国顶级奢侈品牌，以手工皮具闻名，2023年营收134亿欧元，利润率高达40%，Birkin包二手价常超原价。",ez:"最保值的包"},
  {rank:6,cat:'core',term:"Kering开云",pro:"法国奢侈品集团，旗下Gucci、Saint Laurent、Balenciaga等，2023年营收196亿欧元，Gucci贡献超50%收入。",ez:"Gucci的东家"},
  {rank:7,cat:'core',term:"Chanel",pro:"法国奢侈品牌，以香奈儿套装和5号香水闻名，2023年营收197亿美元，未上市但利润丰厚。",ez:"经典小黑裙"},
  {rank:8,cat:'core',term:"Prada",pro:"意大利奢侈品牌，以尼龙包和成衣著称，2023年营收47亿欧元，集团市值约1500亿港元。",ez:"尼龙包鼻祖"},
  {rank:9,cat:'core',term:"Burberry",pro:"英国奢侈品牌，以风衣和格纹闻名，2023年营收30亿英镑，正转型高端化。",ez:"英伦格子风"},
  {rank:10,cat:'core',term:"Cartier卡地亚",pro:"法国珠宝品牌，隶属历峰集团，以Love手镯和Tank腕表闻名，2023年营收超100亿欧元。",ez:"珠宝界的皇帝"},
  {rank:11,cat:'core',term:"Tiffany",pro:"美国珠宝品牌，以钻石订婚戒指闻名，2021年被LVMH以158亿美元收购，2023年营收约50亿美元。",ez:"蒂芙尼蓝"},
  {rank:12,cat:'core',term:"蔻驰",pro:"美国轻奢品牌，以皮具为主，2023年营收约50亿美元，母公司Tapestry集团市值约100亿美元。",ez:"轻奢入门款"},
  {rank:13,cat:'core',term:"中国奢侈品消费",pro:"2023年中国奢侈品消费占全球约22%，达5900亿元人民币，预计2025年成为最大市场。",ez:"中国人买奢侈品多"},
  {rank:14,cat:'core',term:"免税店",pro:"免税店免除关税和消费税，全球最大免税商中免集团2023年营收约500亿元，三亚店年销超300亿。",ez:"买奢侈品便宜的地方"},
  {rank:15,cat:'core',term:"中免",pro:"中国旅游集团中免股份有限公司，全球最大免税零售商，2023年营收约500亿元，市值超2000亿。",ez:"中国免税老大"},
  {rank:16,cat:'tech',term:"手工工艺",pro:"奢侈品强调手工制作，如Hermès一个Birkin包需18小时手工完成，工匠需培训5年以上。",ez:"纯手工打造"},
  {rank:17,cat:'tech',term:"皮革鞣制",pro:"皮革处理工艺，如Hermès使用植物鞣制，耗时数月，确保皮质柔软耐用。",ez:"皮料处理技术"},
  {rank:18,cat:'tech',term:"高级定制",pro:"Haute Couture，为个人量身定制，Chanel每年发布两季高定系列，每件耗时数百小时。",ez:"量身定做的高端衣服"},
  {rank:19,cat:'tech',term:"珠宝镶嵌",pro:"将宝石固定在金属上的工艺，Cartier使用微镶技术，每颗钻石误差小于0.01毫米。",ez:"宝石固定技术"},
  {rank:20,cat:'tech',term:"腕表机芯",pro:"手表内部机械结构，如Patek Philippe机芯由数百零件组成，精度达每日误差±2秒。",ez:"手表的心脏"},
  {rank:21,cat:'tech',term:"防伪技术",pro:"奢侈品采用RFID芯片、全息标签等防伪，如Louis Vuitton植入微芯片，可追溯真伪。",ez:"防假货技术"},
  {rank:22,cat:'tech',term:"面料创新",pro:"使用高科技面料，如Stella McCartney用再生聚酯，Gucci推出Demetra环保皮革。",ez:"新布料科技"},
  {rank:23,cat:'tech',term:"数字孪生",pro:"虚拟复制产品，用于NFT和元宇宙，如Gucci在Roblox销售虚拟包，售价超实体。",ez:"虚拟奢侈品"},
  {rank:24,cat:'tech',term:"供应链追溯",pro:"通过区块链追踪原料来源，如LVMH使用AURA平台，确保钻石从矿场到门店透明。",ez:"查来源的技术"},
  {rank:25,cat:'tech',term:"环保染色",pro:"减少水污染和化学品使用，如Prada使用再生尼龙ECONYL，染色过程节水90%。",ez:"绿色染色"},
  {rank:26,cat:'biz',term:"垂直整合",pro:"控制从原料到零售全链条，如Hermès拥有自家牧场和皮具工坊，确保品质。",ez:"自己管全部"},
  {rank:27,cat:'biz',term:"限量发售",pro:"制造稀缺，如Supreme每周限量，Nike联名款秒空，二级市场溢价数倍。",ez:"抢不到就贵了"},
  {rank:28,cat:'biz',term:"品牌授权",pro:"授权第三方生产，如Gucci眼镜授权给霞飞诺，年授权费收入超10亿欧元。",ez:"牌子租给别人用"},
  {rank:29,cat:'biz',term:"直营零售",pro:"品牌自营门店，如Louis Vuitton全球460家直营店，控制体验和利润。",ez:"自己开店卖"},
  {rank:30,cat:'biz',term:"电商渠道",pro:"线上销售，2023年奢侈品电商占比约22%，如Farfetch年GMV超40亿美元。",ez:"网上卖奢侈品"},
  {rank:31,cat:'biz',term:"二手市场",pro:"二手奢侈品交易，2023年全球规模约400亿美元，The RealReal年营收超5亿美元。",ez:"卖二手奢侈品"},
  {rank:32,cat:'biz',term:"联名合作",pro:"品牌跨界合作，如Louis Vuitton x Supreme，引发抢购，销售额超1亿欧元。",ez:"两个牌子一起出"},
  {rank:33,cat:'biz',term:"会员体系",pro:"忠诚度计划，如Cartier会员积分兑换服务，高端客户年消费超百万。",ez:"VIP制度"},
  {rank:34,cat:'biz',term:"体验营销",pro:"打造沉浸式体验，如Dior在巴黎蒙田大道开设咖啡馆，吸引客流。",ez:"让你感受品牌"},
  {rank:35,cat:'biz',term:"快闪店",pro:"临时店铺制造热度，如Chanel在东京开设限时咖啡店，排队数小时。",ez:"临时开店"},
  {rank:36,cat:'finance',term:"毛利率",pro:"奢侈品毛利率通常70%-80%，如Hermès毛利率达80%，远高于一般消费品。",ez:"赚差价比例"},
  {rank:37,cat:'finance',term:"同店增长",pro:"可比门店销售增长，LVMH 2023年同店增长8%，反映品牌健康度。",ez:"老店卖得更多"},
  {rank:38,cat:'finance',term:"EBITDA利润率",pro:"息税折旧摊销前利润率，奢侈品平均30%-40%，如Gucci达40%。",ez:"赚钱效率"},
  {rank:39,cat:'finance',term:"库存周转率",pro:"库存销售速度，奢侈品周转慢，如Burberry年周转约1.5次，避免打折。",ez:"货卖得快慢"},
  {rank:40,cat:'finance',term:"市值",pro:"上市公司总市值，LVMH市值超4000亿欧元，全球最大奢侈品公司。",ez:"公司值多少钱"}
];
