window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['os_infra'] = [
  {rank:1,cat:'core',term:"信创",pro:"信创即信息技术应用创新，旨在实现IT基础设施自主可控，2022年市场规模达1.8万亿元。",ez:"国产替代"},
  {rank:2,cat:'core',term:"操作系统",pro:"操作系统是管理计算机硬件与软件资源的系统软件，国内主要产品有openEuler、统信UOS、麒麟OS等。",ez:"电脑的管家"},
  {rank:3,cat:'core',term:"openEuler",pro:"openEuler是华为开源的企业级Linux服务器操作系统，截至2023年装机量超300万套。",ez:"华为系服务器系统"},
  {rank:4,cat:'core',term:"OpenHarmony",pro:"OpenHarmony是开源分布式操作系统，由开放原子开源基金会运营，支持多种终端设备。",ez:"华为开源系统"},
  {rank:5,cat:'core',term:"统信UOS",pro:"统信UOS是统信软件基于Linux开发的操作系统，支持国产CPU，已适配超10万款软硬件。",ez:"国产桌面系统"},
  {rank:6,cat:'core',term:"麒麟操作系统",pro:"麒麟操作系统由麒麟软件开发，包括银河麒麟和中标麒麟，在政府市场占有率超50%。",ez:"官方用国产系统"},
  {rank:7,cat:'core',term:"数据库",pro:"数据库是存储和管理数据的系统，国产代表有达梦数据库、OceanBase、GaussDB等。",ez:"数据仓库"},
  {rank:8,cat:'core',term:"达梦数据库",pro:"达梦数据库是武汉达梦公司研发的关系型数据库，兼容Oracle，在政务领域广泛应用。",ez:"国产数据库"},
  {rank:9,cat:'core',term:"OceanBase",pro:"OceanBase是蚂蚁集团开发的分布式关系数据库，支持HTAP，TPC-C测试成绩达7.07亿tpmC。",ez:"蚂蚁金服数据库"},
  {rank:10,cat:'core',term:"中间件",pro:"中间件是介于操作系统和应用软件之间的基础软件，国产代表有东方通、宝兰德、普元等。",ez:"软件桥梁"},
  {rank:11,cat:'core',term:"东方通",pro:"东方通是国内领先的中间件厂商，产品包括应用服务器TongWeb，市场占有率约20%。",ez:"国产中间件龙头"},
  {rank:12,cat:'core',term:"宝兰德",pro:"宝兰德专注于企业级中间件，其BES Application Server在电信行业有广泛应用。",ez:"中间件厂商"},
  {rank:13,cat:'core',term:"办公软件",pro:"办公软件包括文字处理、表格、演示等，国产代表有金山WPS、永中Office等。",ez:"写文档软件"},
  {rank:14,cat:'core',term:"ERP",pro:"ERP是企业资源计划系统，国产代表有用友、金蝶，其中用友市占率约30%。",ez:"企业管理软件"},
  {rank:15,cat:'core',term:"国产替代",pro:"国产替代指用国产软硬件替换国外产品，政策推动下2025年信创产业规模预计超2万亿元。",ez:"不用外国货"},
  {rank:16,cat:'tech',term:"Linux内核",pro:"Linux内核是操作系统的核心，开源且可定制，openEuler和麒麟OS均基于其开发。",ez:"系统的心脏"},
  {rank:17,cat:'tech',term:"分布式架构",pro:"分布式架构将系统拆分为多个独立节点协同工作，OceanBase采用此架构实现高可用。",ez:"多台电脑一起干"},
  {rank:18,cat:'tech',term:"容器化",pro:"容器化是一种轻量级虚拟化技术，如Docker，可快速部署应用，信创领域广泛采用。",ez:"打包运行环境"},
  {rank:19,cat:'tech',term:"微服务",pro:"微服务将应用拆分为小型服务独立部署，宝兰德中间件支持微服务架构。",ez:"小模块拼成系统"},
  {rank:20,cat:'tech',term:"云原生",pro:"云原生是一种构建和运行应用的方法，利用云计算弹性，如基于Kubernetes的容器编排。",ez:"为云而生"},
  {rank:21,cat:'tech',term:"自主可控",pro:"自主可控指核心技术自主掌握，避免受制于人，是信创的核心目标。",ez:"自己说了算"},
  {rank:22,cat:'tech',term:"适配认证",pro:"适配认证是国产软硬件兼容性测试，统信UOS已适配超10万款软硬件。",ez:"测试兼容性"},
  {rank:23,cat:'tech',term:"国产CPU",pro:"国产CPU包括鲲鹏、飞腾、龙芯等，麒麟OS和统信UOS均支持这些芯片。",ez:"中国造处理器"},
  {rank:24,cat:'tech',term:"虚拟化",pro:"虚拟化将物理资源抽象为多个虚拟资源，如KVM，在信创服务器中常用。",ez:"一台变多台"},
  {rank:25,cat:'tech',term:"安全可靠",pro:"安全可靠指产品通过国家认证，如安全可靠测评，信创产品需满足高安全标准。",ez:"放心用"},
  {rank:26,cat:'biz',term:"信创产业",pro:"信创产业涵盖基础硬件、基础软件、应用软件等，2023年市场规模约1.8万亿元。",ez:"国产IT产业链"},
  {rank:27,cat:'biz',term:"2+8+N",pro:"2+8+N是信创推进体系：党政+八大行业+其他行业，逐步实现国产替代。",ez:"先政府后行业"},
  {rank:28,cat:'biz',term:"集成商",pro:"集成商负责整合信创产品提供解决方案，如中国软件、太极股份等。",ez:"组装电脑的"},
  {rank:29,cat:'biz',term:"开源社区",pro:"开源社区如openEuler社区，汇聚开发者共同贡献代码，推动信创生态发展。",ez:"程序员一起写代码"},
  {rank:30,cat:'biz',term:"生态建设",pro:"生态建设指软硬件适配、开发者培养等，统信UOS生态适配量超10万。",ez:"拉拢小伙伴"},
  {rank:31,cat:'biz',term:"订阅制",pro:"订阅制是按期付费使用软件，如WPS Office会员，信创厂商逐渐转向此模式。",ez:"租着用"},
  {rank:32,cat:'biz',term:"信创云",pro:"信创云是基于国产软硬件的云平台，如华为云Stack、浪潮云等。",ez:"国产云服务"},
  {rank:33,cat:'biz',term:"政府采购",pro:"政府采购是信创主要驱动力，2023年党政信创采购金额超500亿元。",ez:"政府掏钱买"},
  {rank:34,cat:'biz',term:"替代率",pro:"替代率指国产产品替换进口的比例，目前操作系统替代率约20%。",ez:"换掉多少"},
  {rank:35,cat:'biz',term:"双轨制",pro:"双轨制指新旧系统并行运行，过渡期内信创和原有系统同时使用。",ez:"两条腿走路"},
  {rank:36,cat:'finance',term:"研发投入",pro:"研发投入是信创企业核心支出，如中科曙光2022年研发费用超20亿元。",ez:"花钱搞研发"},
  {rank:37,cat:'finance',term:"毛利率",pro:"毛利率反映产品盈利能力，基础软件企业毛利率通常较高，如金山办公约85%。",ez:"赚头大不大"},
  {rank:38,cat:'finance',term:"市占率",pro:"市占率是市场份额，如达梦数据库在国产数据库市占率约15%。",ez:"占多少市场"},
  {rank:39,cat:'finance',term:"营收增速",pro:"营收增速衡量成长性，信创板块2023年整体营收增速约20%。",ez:"赚钱快不快"},
  {rank:40,cat:'finance',term:"国产化率",pro:"国产化率是国产产品使用比例，如办��软��国产化率约60%。",ez:"国产占多少"}
];
