window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['power_semi'] = [
  {rank:1,cat:'core',term:"功率半导体",pro:"用于电能转换和控制的半导体器件，市场约500亿美元，年增6%，核心包括MOSFET、IGBT、SiC等。",ez:"电力的开关管家"},
  {rank:2,cat:'core',term:"IGBT",pro:"绝缘栅双极型晶体管，电压600V-6500V，2023年市场超80亿美元，英飞凌占25%份额。",ez:"高压大电流开关"},
  {rank:3,cat:'core',term:"MOSFET",pro:"金属氧化物半导体场效应管，低压高频应用，2023年市场约100亿美元，安森美为龙头。",ez:"低压快速开关"},
  {rank:4,cat:'core',term:"碳化硅 SiC",pro:"第三代宽禁带半导体，耐压高、损耗低，2025年市场预计超50亿美元，特斯拉已采用。",ez:"新一代节能材料"},
  {rank:5,cat:'core',term:"氮化镓 GaN",pro:"宽禁带半导体，高频高效，2023年市场约20亿美元，用于快充和5G基站。",ez:"快充黑科技"},
  {rank:6,cat:'core',term:"车规级",pro:"符合AEC-Q101等汽车标准，要求-40~175°C，零缺陷，认证周期18-24个月。",ez:"汽车专用芯片"},
  {rank:7,cat:'core',term:"800V",pro:"高压平台，充电10分钟续航400公里，SiC器件是核心，保时捷Taycan率先量产。",ez:"超快充高压架构"},
  {rank:8,cat:'core',term:"英飞凌",pro:"全球功率半导体龙头，2023年营收约150亿欧元，汽车业务占50%，IGBT市占第一。",ez:"功率芯片老大"},
  {rank:9,cat:'core',term:"ST意法",pro:"欧洲半导体巨头，SiC MOSFET领先，2023年营收170亿美元，汽车和工业占60%。",ez:"欧洲芯片大厂"},
  {rank:10,cat:'core',term:"安森美",pro:"美国功率半导体公司，2023年营收80亿美元，MOSFET和SiC模块主要供应商。",ez:"美国功率芯片商"},
  {rank:11,cat:'core',term:"士兰微",pro:"中国IDM功率半导体厂商，2023年营收约100亿元，产品覆盖IGBT、MOSFET、IPM。",ez:"国产功率IDM"},
  {rank:12,cat:'core',term:"闻泰科技",pro:"收购安世半导体后进入功率领域，2023年营收约600亿元，安世为全球车规级分立器件龙头。",ez:"收购安世的大厂"},
  {rank:13,cat:'core',term:"斯达半导",pro:"中国IGBT模块龙头，2023年营收约40亿元，应用于新能源汽车和工控。",ez:"国产IGBT先锋"},
  {rank:14,cat:'core',term:"时代电气",pro:"中车旗下，高铁IGBT供应商，2023年营收约200亿元，布局SiC产线。",ez:"高铁IGBT王者"},
  {rank:15,cat:'core',term:"功率器件",pro:"包括二极管、晶体管、晶闸管等，2023年全球市场约500亿美元，中国占40%。",ez:"电力电子基础件"},
  {rank:16,cat:'tech',term:"宽禁带半导体",pro:"禁带宽度>2.3eV，如SiC(3.3eV)、GaN(3.4eV)，耐高温高频，效率提升30%。",ez:"不怕热不怕高压"},
  {rank:17,cat:'tech',term:"导通电阻 Rds(on)",pro:"MOSFET导通时漏源电阻，SiC可低至10mΩ，影响导通损耗，每降1mΩ效率升0.5%。",ez:"开关的阻力"},
  {rank:18,cat:'tech',term:"开关频率",pro:"器件每秒开关次数，IGBT可达20kHz，MOSFET可达1MHz，GaN可达10MHz。",ez:"每秒开关多少次"},
  {rank:19,cat:'tech',term:"击穿电压",pro:"器件能承受的最大电压，IGBT可达6500V，SiC MOSFET可达1700V。",ez:"最高耐压值"},
  {rank:20,cat:'tech',term:"封装技术",pro:"如TO-247、D2PAK、模块封装，影响散热和寄生参数，英飞凌XT技术提升可靠性。",ez:"芯片的外壳"},
  {rank:21,cat:'tech',term:"热阻",pro:"器件散热能力，单位°C/W，SiC模块热阻可低至0.3°C/W，需配合散热器。",ez:"散热好坏指标"},
  {rank:22,cat:'tech',term:"寄生电容",pro:"器件内部电容，影响开关速度，SiC寄生电容小，开关损耗低30%。",ez:"芯片的杂散电容"},
  {rank:23,cat:'tech',term:"雪崩耐量",pro:"器件承受过电压能力，单位mJ，SiC MOSFET可达100mJ，防损坏。",ez:"抗过压能力"},
  {rank:24,cat:'tech',term:"体二极管",pro:"MOSFET内部寄生二极管，用于续流，SiC体二极管反向恢复快，损耗低。",ez:"自带的小二极管"},
  {rank:25,cat:'tech',term:"栅极驱动",pro:"控制开关的电压信号，IGBT需±15V，SiC需0-20V，驱动芯片如英飞凌1ED系列。",ez:"开关的遥控器"},
  {rank:26,cat:'biz',term:"IDM模式",pro:"设计制��封测一体化，如英飞凌、士兰微，投资大但利润高，毛利率可达40%。",ez:"自己造自己卖"},
  {rank:27,cat:'biz',term:"Fabless模式",pro:"无晶圆厂，只设计，如斯达半导，轻资产，毛利率30%左右。",ez:"只设计不生产"},
  {rank:28,cat:'biz',term:"Foundry模式",pro:"代工厂，如台积电、华虹，功率代工毛利率20-30%。",ez:"代工芯片"},
  {rank:29,cat:'biz',term:"车规认证",pro:"AEC-Q101、IATF16949，认证周期2年，费用数百万，是进入汽车供应链门槛。",ez:"汽车入场券"},
  {rank:30,cat:'biz',term:"国产替代",pro:"中国功率自给率约30%，政策推动，斯达、士兰微等份额从5%升至15%。",ez:"用国产芯片"},
  {rank:31,cat:'biz',term:"垂直整合",pro:"从衬底到模块全产业链，如SiC领域Wolfspeed，成本降低20%。",ez:"全包了"},
  {rank:32,cat:'biz',term:"长协订单",pro:"客户与供应商签订2-5年合同，锁定产能和价格，英飞凌与车企签超50亿欧元。",ez:"长期包产合同"},
  {rank:33,cat:'biz',term:"产能扩张",pro:"2023年全球SiC产能翻倍，英飞凌投资50亿欧元建厂，2025年投产。",ez:"疯狂建厂"},
  {rank:34,cat:'biz',term:"模块化方案",pro:"将多个芯片封装成模块，如英飞凌HybridPACK，功率密度提升30%。",ez:"集成模块"},
  {rank:35,cat:'biz',term:"系统解决方案",pro:"提供芯片+驱动+散热整体方案，如ST的Stellar平台，客户开发周期缩短6个月。",ez:"打包服务"},
  {rank:36,cat:'finance',term:"毛利率",pro:"功率半导体龙头毛利率40-50%，如英飞凌45%，斯达半导35%，受价格战影响。",ez:"赚钱能力"},
  {rank:37,cat:'finance',term:"研发投入",pro:"英飞凌年研发投入约15亿欧元，占营收10%，SiC研发占比更高。",ez:"研发花钱"},
  {rank:38,cat:'finance',term:"资本开支",pro:"建厂和设备投资，英飞凌2023年资本开支30亿欧元，占营收20%。",ez:"买设备建厂"},
  {rank:39,cat:'finance',term:"库存周转率",pro:"功率器件库存周转约3-4次/年，缺芯时降至2次，反映供需。",ez:"库存卖得快慢"},
  {rank:40,cat:'finance',term:"市占率",pro:"英飞凌全球功率市占率19%，MOSFET市占率11%，SiC市占率30%。",ez:"市场份额"}
];
