/* IndustryLens — 房地产 关键词百科 */
KEYWORDS_DB['property'] = [
{rank:1,cat:'core',term:"三道红线",pro:"剔除预收款的资产负债率<70%、净负债率<100%、现金短债比>1。",ez:"房企的三条生命线。"},
{rank:2,cat:'finance',term:"土储",pro:"土地储备。可售面积决定未来3年销售。",ez:"手里有多少地。"},
{rank:3,cat:'finance',term:"货值",pro:"土储对应的货币价值。",ez:"地能卖多少钱。"},
{rank:4,cat:'finance',term:"去化率",pro:"销售/可售。健康>70%。",ez:"开盘卖掉多少。"},
{rank:5,cat:'finance',term:"毛利率",pro:"房企毛利15-25%。2024年行业承压。",ez:"卖房毛利。"},
{rank:6,cat:'finance',term:"预收账款",pro:"预售收到的钱。是未来收入的先行指标。",ez:"先收钱的部分。"},
{rank:7,cat:'biz',term:"保障房",pro:"政府收储+保障性住房建设。新模式核心。",ez:"政府保障的房子。"},
{rank:8,cat:'core',term:"保交楼",pro:"2022年以来国家重点。稳民生。",ez:"烂尾楼要交付。"},
{rank:9,cat:'biz',term:"城市更新",pro:"一线城市增长点。代替新增用地。",ez:"旧城改造。"},
{rank:10,cat:'biz',term:"商业地产",pro:"SM/万达/龙湖天街/太古。REITs退出通道打通。",ez:"商场/写字楼。"},
{rank:11,cat:'biz',term:"物业",pro:"在管面积核心指标。碧桂园服务/万物云龙头。",ez:"物业管理。"},
{rank:12,cat:'biz',term:"长租公寓",pro:"魔方/冠寓/自如。保租房REITs上市通道。",ez:"长期租的房。"},
{rank:13,cat:'core',term:"REITs",pro:"不动产投资信托基金。中国公募REITs 2021年落地。",ez:"房产证券化。"},
{rank:14,cat:'biz',term:"央国企 vs 民营",pro:"央国企稳健（保利/华润）、民营激进（恒大/碧桂园暴雷）。",ez:"国企 vs 民企。"},
{rank:15,cat:'finance',term:"销售回款",pro:"现金流核心。房企生命线。",ez:"卖房收钱。"},
{rank:16,cat:'finance',term:"存销比",pro:"可售面积/月均销售。>14个月警示。",ez:"库存够卖几个月。"},
{rank:17,cat:'biz',term:"地王",pro:"高价拿地。2024年一线城市频现。",ez:"最贵的那块地。"},
{rank:18,cat:'core',term:"集中供地",pro:"22城2021试点，2024年退出。",ez:"集中卖地政策。"},
{rank:19,cat:'core',term:"房地产税",pro:"多次提出未落地。长期悬念。",ez:"持有房子要交的税。"},
{rank:20,cat:'biz',term:"城市群 vs 县城",pro:"一二线城市群量稳价稳，县城量价下行。",ez:"大城市 vs 小城市。"},
];