window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['rpa'] = [
  {rank:1,cat:'core',term:"RPA",pro:"机器人流程自动化，通过软件机器人模拟人类操作，实现业务流程自动化。2023年全球RPA市场规模达29.5亿美元。",ez:"软件机器人帮你干活"},
  {rank:2,cat:'core',term:"流程自动化",pro:"将重复性、规则明确的业务流程交由软件机器人执行，提升效率。企业部署RPA后平均节省30%的运营成本。",ez:"让机器做重复工作"},
  {rank:3,cat:'core',term:"UiPath",pro:"全球领先的RPA平台，2023年营收13.1亿美元，客户包括多家财富500强企业。提供端到端自动化解决方案。",ez:"RPA行业老大"},
  {rank:4,cat:'core',term:"Automation Anywhere",pro:"知名RPA厂商，其IQ Bot融合AI能力，可处理非结构化数据。全球客户超1万家，覆盖金融、医疗等行业。",ez:"RPA老牌玩家"},
  {rank:5,cat:'core',term:"Blue Prism",pro:"英国RPA公司，首创数字化劳动力概念。2022年被SS&C Technologies以16亿美元收购，客户包括NHS、西门子等��",ez:"RPA先驱之一"},
  {rank:6,cat:'core',term:"来也科技",pro:"中国领先的RPA厂商，旗下UiBot产品用户超200万。2021年完成C+轮融资，估值超10亿美元。",ez:"中国RPA领头羊"},
  {rank:7,cat:'core',term:"达观数据",pro:"中国智能文本处理与RPA厂商，其RPA产品结合NLP技术，应用于金融、政务等领域。累计融资超5亿元。",ez:"文本处理+RPA"},
  {rank:8,cat:'core',term:"云扩科技",pro:"中国RPA厂商，提供云原生RPA平台，支持公有云、私有云部署。产品包括云扩编辑器、机器人等，客户超3000家。",ez:"云原生RPA"},
  {rank:9,cat:'core',term:"IPA",pro:"智能流程自动化，融合RPA与AI技术，如OCR、NLP、机器学习，处理复杂任务。预计到2025年IPA市场将达200亿美元。",ez:"RPA+AI升级版"},
  {rank:10,cat:'core',term:"智能流程自动化",pro:"即IPA，结合RPA和AI实现端到端自动化，可处理非结构化数据。例如UiPath的AI Center提供模型训练能力。",ez:"更聪明的自动化"},
  {rank:11,cat:'core',term:"机器人流程自动化",pro:"RPA全称，通过软件机器人模拟键盘鼠��操作，执行重复任务。典型应用：财务对账、数据录入等。",ez:"就是RPA"},
  {rank:12,cat:'core',term:"数字化劳动力",pro:"由RPA机器人组成的虚拟员工队伍，可7x24小时工作。Blue Prism提出此概念，企业平均部署50+机器人。",ez:"虚拟员工"},
  {rank:13,cat:'core',term:"非侵入式集成",pro:"RPA通过UI交互集成现有系统，无需修改原有代码。部署周期通常为2-4周，远低于传统API集成。",ez:"不动现有系统"},
  {rank:14,cat:'core',term:"屏幕抓取",pro:"RPA技术之一，从应用程序界面抓取数据。例如Automation Anywhere的IQ Bot可抓取PDF、图片中的文字。",ez:"从屏幕取数据"},
  {rank:15,cat:'core',term:"流程挖掘",pro:"通过分析系统日志发现真实流程，识别自动化机会。Celonis是领先厂商，与UiPath等合作，可提升30%自动化效率。",ez:"找能自动化的流程"},
  {rank:16,cat:'tech',term:"OCR",pro:"光学字符识别，将图片中的文字转为可编辑文本。RPA中常用，如识别发票、身��证。准确率可达99%以上。",ez:"图片转文字"},
  {rank:17,cat:'tech',term:"NLP",pro:"自然语言处理，让机器理解人类语言。RPA结合NLP可处理邮件、客服对话。达观数据NLP技术用于智能文档处理。",ez:"让机器懂人话"},
  {rank:18,cat:'tech',term:"计算机视觉",pro:"让计算机识别图像内容。RPA中用于验证码识别、屏幕元素定位。UiPath的Computer Vision可处理虚拟桌面。",ez:"机器看懂图像"},
  {rank:19,cat:'tech',term:"API集成",pro:"应用程序编程接口，允许系统间直接通信。RPA也支持API调用，但非侵入式集成是其主要优势。",ez:"系统间直连"},
  {rank:20,cat:'tech',term:"低代码平台",pro:"通过拖拽组件快速开发应用。RPA厂商提供低代码设计器，如云扩编辑器，降低开发门槛。",ez:"拖拽做软件"},
  {rank:21,cat:'tech',term:"机器人编排",pro:"管理多个RPA机器人的调度、监控和部署。UiPath Orchestrator可管理10万个机器人并发运行。",ez:"管理机器人团队"},
  {rank:22,cat:'tech',term:"无人值守机器人",pro:"后台自动运行，无需人工干预。常用于夜间批量处理，如财务结账。Automation Anywhere的Bot Runner支持无人值守。",ez:"自动后台跑"},
  {rank:23,cat:'tech',term:"有人值守机器人",pro:"需要人工触发或协助的RPA机器人。常用于客服辅助，如自动查询客户信息。",ez:"人机配合"},
  {rank:24,cat:'tech',term:"流程记录器",pro:"录制用户操作并生成自动化脚本。UiPath的Recorder可录制鼠标键盘动作，快速创建RPA流程。",ez:"录操作变脚本"},
  {rank:25,cat:'tech',term:"自动化测试",pro:"使用RPA进行软件测试，模拟用户操作。例如UiPath Test Suite支持自动化回归测试，减少80%测试时间。",ez:"机器人测软件"},
  {rank:26,cat:'biz',term:"RPA即服务",pro:"RPA as a Service，云交付模式。按需付费，降低初期成本。云扩科技提供RPA SaaS，客户可快速上线。",ez:"租用RPA"},
  {rank:27,cat:'biz',term:"卓越中心",pro:"CoE，企业内RPA管理团队，负责战略、治理、最佳实践。通常CoE可提升50%的自动化项目成功率。",ez:"RPA核心团队"},
  {rank:28,cat:'biz',term:"自动化优先",pro:"企业战略，优先考虑自动化解决方案。UiPath倡导此理念，可节省20%的人力成本。",ez:"先想能不能自动"},
  {rank:29,cat:'biz',term:"业务流程外包",pro:"BPO，将流程外包给第三方。RPA可替代部分BPO，降低成本50%以上，如财务、HR流程。",ez:"外包给机器人"},
  {rank:30,cat:'biz',term:"数字化转型",pro:"企业利用数字技术变革业务。RPA是数字化转型的关键工具，2023年企业RPA采用率达60%。",ez:"企业数字化"},
  {rank:31,cat:'biz',term:"超级自动化",pro:"Gartner提出的概念，结合RPA、AI、流程挖掘等，实现端到端自动化。预计到2025年市场规模超800亿美元。",ez:"全面自动化"},
  {rank:32,cat:'biz',term:"人机协作",pro:"人类与RPA机器人协同工作。例如客服人员调用机器人查询信息，提升效率30%以上。",ez:"人+机器一起干"},
  {rank:33,cat:'biz',term:"合规自动化",pro:"利用RPA确保流程合规，如自动记录审计日志。金融机构使用RPA满足监管要求，减少人为错误。",ez:"自动合规"},
  {rank:34,cat:'biz',term:"财务自动化",pro:"RPA在财务领域的应用，如发票处理、对账、报销。可缩短80%的处理时间，准确率近100%。",ez:"财务机器人"},
  {rank:35,cat:'biz',term:"客服自动化",pro:"RPA辅助客服，自动查询订单、更新信息。来也科技客服机器人可处理70%的常见问题。",ez:"客服机器人"},
  {rank:36,cat:'finance',term:"投资回报率",pro:"ROI，衡量RPA项目收益。典型RPA项目ROI在200%-500%，平均6-12个月回本。",ez:"投入产出比"},
  {rank:37,cat:'finance',term:"总拥有成本",pro:"TCO，包含软件许可、实施、维护等费用。RPA TCO通常低于传统IT项目，3年TCO可节省40%。",ez:"总成本"},
  {rank:38,cat:'finance',term:"年度经常性收入",pro:"ARR，SaaS模式下的关键指标。UiPath 2023年ARR为13.1亿美元，同比增长24%。",ez:"年订阅收入"},
  {rank:39,cat:'finance',term:"客户留存率",pro:"衡量客户续约情况。RPA行业平均留存率超90%，UiPath客户留存率达95%。",ez:"客户留下比例"},
  {rank:40,cat:'finance',term:"部署成本",pro:"实施RPA项目的初始投入，包括软件、咨询、培训。中小企业部署成本约5-10万元，大型企业可达百万。",ez:"上线花多少钱"}
];
