window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['storage'] = [
  {rank:1,cat:'core',term:"DRAM",pro:"动态随机存取存储器，易失性，需定期刷新。2024年全球市场规模约800亿美元，三星、海力士、美光三巨头占95%以上份额。",ez:"电脑内存条，断电数据丢"},
  {rank:2,cat:'core',term:"NAND Flash",pro:"非易失性闪存，断电保留数据。2024年市场规模约600亿美元，主要用于SSD和U盘，层数已突破232层。",ez:"固态硬盘和U盘的核心"},
  {rank:3,cat:'core',term:"3D NAND",pro:"垂直堆叠存储单元的技术，当前主流232层，长江存储Xtacking 3.0实现232层，三星V-NAND达236层。",ez:"把存储单元叠高楼，容量翻倍"},
  {rank:4,cat:'core',term:"HBM",pro:"高带宽存储器，通过TSV垂直堆叠DRAM，HBM3带宽达819GB/s，英伟达H100搭载80GB HBM3，三星、海力士主导。",ez:"AI显卡专用高带宽内存"},
  {rank:5,cat:'core',term:"DDR5",pro:"第五代双倍数据率同步DRAM，速率4800-8400Mbps，电压1.1V，2024年渗透率超50%，三星、海力士量产。",ez:"最新一代内存条，更快更省电"},
  {rank:6,cat:'core',term:"LPDDR",pro:"低功耗双倍数据率DRAM，用于移动设备，LPDDR5X速率8533Mbps，功耗降低20%，三星、美光主要供应商。",ez:"手机里的低功耗内存"},
  {rank:7,cat:'core',term:"SSD",pro:"固态硬盘，基于NAND Flash，2024年全球出货量超3亿块，PCIe 5.0 SSD顺序读取达14GB/s，主控厂商有慧荣、群联。",ez:"电脑硬盘的升级版，速度快"},
  {rank:8,cat:'core',term:"NAND Flash",pro:"非易失性闪存，断电保留数据。2024年市场规模约600亿美元，主要用于SSD和U盘，层数已突破232层。",ez:"固态硬盘和U盘的核心"},
  {rank:9,cat:'core',term:"晶圆",pro:"半导体芯片的基板，存储芯片常用12英寸晶圆，单晶圆可切割数百颗芯片，三星、海力士拥有全球最大产能。",ez:"做芯片的圆形硅片"},
  {rank:10,cat:'core',term:"制程工艺",pro:"芯片制造精度，存储芯片先进制程为10nm级（1z nm），DRAM已进入1α nm（约15nm），线宽越小功耗越低。",ez:"芯片的雕刻精度，越小越强"},
  {rank:11,cat:'core',term:"存储密度",pro:"单位面积或体积的存储容量，3D NAND通过堆叠提升密度，232层相比96层密度提升2.4倍，TLC每单元3bit。",ez:"同样大小能存更多数据"},
  {rank:12,cat:'core',term:"读写延迟",pro:"数据存取响应时间，DRAM延迟约10ns，NAND Flash延迟约100μs，SSD通过NVMe协议降低延迟至微秒级。",ez:"数据存取的等待时间"},
  {rank:13,cat:'core',term:"耐久度",pro:"存储单元可擦写次数，SLC约10万次，MLC约1万次，TLC约3000次，QLC约1000次，3D NAND通过优化延长寿命。",ez:"闪存能写多少次"},
  {rank:14,cat:'core',term:"ECC纠错",pro:"错误检查和纠正技术，NAND Flash需ECC确保数据完整性，LDPC码可纠正每KB 40位错误，主控集成ECC引擎。",ez:"自动修复存储错误"},
  {rank:15,cat:'core',term:"NVMe",pro:"非易失性内存标准，基于PCIe总线，SSD顺序读写可达14GB/s，延迟低于10μs，取代AHCI成为主流接口。",ez:"SSD的高速接口协议"},
  {rank:16,cat:'tech',term:"3D NAND",pro:"垂直堆叠存储单元的��术，当前主流232层，长江存储Xtacking 3.0实现232层，三星V-NAND达236层。",ez:"把存储单元叠高楼，容量翻倍"},
  {rank:17,cat:'tech',term:"TSV",pro:"硅通孔技术，垂直贯穿硅片的电连接，用于HBM堆叠DRAM，间距小于10μm，实现高带宽低功耗。",ez:"芯片内部打孔垂直连"},
  {rank:18,cat:'tech',term:"TLC",pro:"三层单元，每单元存储3bit，成本低，主流消费级SSD采用，耐久度约3000次P/E，三星、长江存储量产。",ez:"每个存储单元存3位数据"},
  {rank:19,cat:'tech',term:"QLC",pro:"四层单元，每单元存储4bit，成本更低，耐久度约1000次P/E，用于大容量SSD，美光、英特尔量产。",ez:"每个存储单元存4位数据"},
  {rank:20,cat:'tech',term:"SLC",pro:"单层单元，每单元存储1bit，速度快、耐久度高（10万次），用于企业级SSD和缓存，价格昂贵。",ez:"每个存储单元存1位数据"},
  {rank:21,cat:'tech',term:"MLC",pro:"多层单元，每单元存储2bit，平衡性能与成本，耐久度约1万次，曾用于高端消费SSD，现逐渐被TLC取代。",ez:"每个存储单元存2位数据"},
  {rank:22,cat:'tech',term:"Xtacking",pro:"长江存储独创的3D NAND架构，将存储单元和外围电路分开制造再键合，实现更高密度和性能，232层产品已量产。",ez:"长江存储的堆叠黑科技"},
  {rank:23,cat:'tech',term:"V-NAND",pro:"三星的3D NAND品牌，采用垂直堆叠，2024年量产236层，单芯片容量1Tb，用于SSD和移动存储。",ez:"三星的垂直闪存技术"},
  {rank:24,cat:'tech',term:"CMOS",pro:"互补金属氧化物半导体，用于存储芯片外围电路，先进制程如28nm，与存储单元集成提升性能。",ez:"芯片的周边控制电路"},
  {rank:25,cat:'tech',term:"LDPC",pro:"低密度奇偶校验码，高效纠错算法，用于NAND Flash ECC，可纠正每KB 40位错误，提升SSD可靠性。",ez:"一种强力纠错技术"},
  {rank:26,cat:'biz',term:"三星",pro:"全球最大存储芯片厂商，2024年DRAM市占率约40%，NAND约35%，拥有最先进制程和最大产能，引领技术迭代。",ez:"存储芯片老大，韩国巨头"},
  {rank:27,cat:'biz',term:"海力士",pro:"韩国第二大存储厂商，2024年DRAM市占率约28%，NAND约20%，HBM技术领先，为英伟达供应HBM3。",ez:"韩国存储双雄之一"},
  {rank:28,cat:'biz',term:"美光",pro:"美国唯一存储芯片大厂，2024年DRAM市占率约25%，NAND约12%，1β制程DRAM已量产，全球布局。",ez:"美国存储芯片独苗"},
  {rank:29,cat:'biz',term:"长江存储",pro:"中国3D NAND厂商，2024年量产232层，采用Xtacking技术，全球市占率约5%，受美国制裁但持续创新。",ez:"中国闪存突破者"},
  {rank:30,cat:'biz',term:"长鑫存储",pro:"中国DRAM厂商，2024年量产DDR4/LPDDR4，19nm制程，市占率约1%，致力于国产替代。",ez:"中国内存芯片新星"},
  {rank:31,cat:'biz',term:"慧荣科技",pro:"全球领先SSD主控芯片设计公司，2024年市占率超30%，产品覆盖消费级和企业级，支持PCIe 5.0。",ez:"SSD主控芯片龙头"},
  {rank:32,cat:'biz',term:"群联电子",pro:"台湾SSD主控及存储方案厂商，2024年市占率约25%，提供完整SSD解决方案，与NAND原厂紧密合作。",ez:"台湾SSD主控大厂"},
  {rank:33,cat:'biz',term:"英特尔",pro:"曾与美光合作3D XPoint，后退出存储业务，2024年出售SSD业务给海力士，现主要提供Optane持久内存。",ez:"存储领域的老牌玩家"},
  {rank:34,cat:'biz',term:"西部数据",pro:"全球第二大机械硬盘厂商，同时生产NAND Flash和SSD，2024年NAND市占率约10%，与铠侠合资。",ez:"硬盘巨头也做闪存"},
  {rank:35,cat:'biz',term:"铠侠",pro:"原东芝存储器，2024年NAND市占率约15%，与西部数据合资，生产BiCS Flash，技术领先。",ez:"日本闪存大厂"},
  {rank:36,cat:'finance',term:"营收",pro:"存储芯片公司主要收入来源，三星2024年存储营收约600亿美元，海力士约400亿美元，美光约250亿美元。",ez:"公司卖芯片赚的钱"},
  {rank:37,cat:'finance',term:"毛利率",pro:"存储芯片行业毛利率波动大，2024年三星存储毛利率约40%，海力士约35%，美光约30%，受供需影响。",ez:"卖芯片的利润比例"},
  {rank:38,cat:'finance',term:"资本支出",pro:"存储厂商用于建厂和设备的投资，三星2024年资本支出约300亿美元，海力士约150亿美元，用于扩产先进制程。",ez:"公司买设备建厂的钱"},
  {rank:39,cat:'finance',term:"市占率",pro:"各厂商在DRAM/NAND市场的份额，2024年DRAM三巨头占95%，NAND六家占98%，集中度高。",ez:"公司产品卖了多少份额"},
  {rank:40,cat:'finance',term:"ASP",pro:"平均销售价格，存储芯片价格波动剧烈，2024年DRAM ASP约5美元/GB，NAND约0.1美元/GB，周期性强。",ez:"每颗芯片的平均售价"}
];
