window.KEYWORDS_DB = window.KEYWORDS_DB || {};
KEYWORDS_DB['threeDPrint'] = [
  {rank:1,cat:'core',term:"增材制造",pro:"与减材制造相对，通过逐层堆积材料构建三维物体。2022年全球市场规模达150亿美元，预计2030年超600亿美元。",ez:"3D打印的学名"},
  {rank:2,cat:'core',term:"FDM",pro:"熔融沉积成型，热塑性丝材加热挤出逐层堆积。Stratasys专利1992年，占消费级市场70%以上。",ez:"热熔丝堆叠"},
  {rank:3,cat:'core',term:"SLA",pro:"光固化成型，紫外激光固化液态光敏树脂。3D Systems于1986年发明，精度达0.01mm。",ez:"激光照树脂"},
  {rank:4,cat:'core',term:"SLS",pro:"选择性激光烧结，激光熔融粉末材料。EOS公司主导工业市场，成型尺寸可达700mm。",ez:"激光烧结粉末"},
  {rank:5,cat:'core',term:"金属打印",pro:"直接制造金属零件，包括SLM、EBM等技术。2023年金属打印市场占增材制造15%，铂力特国内领先。",ez:"打印金属件"},
  {rank:6,cat:'core',term:"光固化",pro:"利用光敏树脂在光照下固化的技术，包括SLA、DLP、LCD。精度高，表面质量好，用于珠宝、牙科。",ez:"光照变固体"},
  {rank:7,cat:'core',term:"医疗打印",pro:"3D打印用于医疗植入物、手术导板、生物打印。2022年医疗应用占市场15%，骨科植入物增长最快。",ez:"打印人体零件"},
  {rank:8,cat:'core',term:"工业打印",pro:"用于航空航天、汽车等领域的直接零件制造。GE航空LEAP发动机燃油喷嘴已生产超10万个。",ez:"工业级打印"},
  {rank:9,cat:'core',term:"EOS",pro:"德国EOS是全球领先的工业3D打印系统制造商，专注于SLS和金属打印，2023年营收超5亿欧元。",ez:"工业打印巨头"},
  {rank:10,cat:'core',term:"Stratasys",pro:"美国公司，FDM技术发明者，与MakerBot合并，2023年营收约6.3亿美元，专利超1000项。",ez:"FDM鼻祖"},
  {rank:11,cat:'core',term:"铂力特",pro:"中国金属3D打印龙头，科创板上市，2023年营收超12亿元，服务航空航天客户如中国商飞。",ez:"中国金属打印一哥"},
  {rank:12,cat:'core',term:"华曙高科",pro:"中国工业级3D打印领跑者，提供SLS和金属打印，2023年营收超5亿元，海外收入占比30%。",ez:"国产工业打印"},
  {rank:13,cat:'core',term:"SLM",pro:"选择性激光熔化，金属粉末完全熔化，致密度达99.9%以上，用于航空航天复杂零件。",ez:"金属粉末熔融"},
  {rank:14,cat:'core',term:"DLP",pro:"数字光处理，用投影仪固化树脂，速度比SLA快，精度0.05mm，消费级光固化常用。",ez:"投影固化"},
  {rank:15,cat:'core',term:"生物打印",pro:"打印活细胞和组织，用于药物测试和再生医学。2023年Organovo公司首次打印肝组织。",ez:"打印活细胞"},
  {rank:16,cat:'tech',term:"层高",pro:"每层打印厚度，FDM典型0.1-0.3mm，SLA可达0.025mm，层高越小表面越光滑但时间越长。",ez:"打印层厚度"},
  {rank:17,cat:'tech',term:"支撑结构",pro:"悬空部分需添加支撑，FDM常用树状支撑，SLA需手动去除，金属打印多用晶格支撑。",ez:"悬空处的支架"},
  {rank:18,cat:'tech',term:"后处理",pro:"打印后去除支撑、打磨、抛光、热处理等。SLS零件需清粉，金属件需去应力退火。",ez:"打印完的修整"},
  {rank:19,cat:'tech',term:"STL文件",pro:"3D打印标准文件格式，由3D Systems开发，用三角形网格描述表面，文件大小可达数百MB。",ez:"打印文件格式"},
  {rank:20,cat:'tech',term:"G-code",pro:"数控编程语言，控制打印机运动、温度、挤出量。FDM打印机直接执行G-code指令。",ez:"打印机指令"},
  {rank:21,cat:'tech',term:"填充密度",pro:"内部填充百分比，0%空心，100%实心。常见20%蜂窝填充，兼顾强度与省料。",ez:"内部实心程度"},
  {rank:22,cat:'tech',term:"光敏树脂",pro:"SLA/DLP专用材料，遇紫外光固化。种类包括标准、柔性、耐高温，价格约200-500元/升。",ez:"光照凝固的液体"},
  {rank:23,cat:'tech',term:"PLA",pro:"聚乳酸，生物降解塑料，FDM最常用，熔点约170°C，无毒无味，适合家用。",ez:"玉米塑料"},
  {rank:24,cat:'tech',term:"ABS",pro:"丙烯腈-丁二烯-苯乙烯共聚物，强度高但需加热床，收缩率约0.5%，用于功能原型。",ez:"工程塑料"},
  {rank:25,cat:'tech',term:"钛合金",pro:"常用金属打印材料，如Ti6Al4V，强度高耐腐蚀，用于航空医疗，成本约3000元/公斤。",ez:"打印钛金属"},
  {rank:26,cat:'biz',term:"按需制造",pro:"客户上传设计，平台打印后发货。Protolabs 2023年营收4.8亿美元，交期1-3天。",ez:"随时下单打印"},
  {rank:27,cat:'biz',term:"分布式制造",pro:"多个地点就近打印，减少物流。UPS与SAP合作，全球100+门店提供3D打印服务。",ez:"就近打印"},
  {rank:28,cat:'biz',term:"设备销售",pro:"3D打印机硬件销售，Stratasys、EOS等主要收入来源，工业机单价10万-100万美元。",ez:"卖打印机"},
  {rank:29,cat:'biz',term:"材料销售",pro:"耗材销售，利润率高达60-80%。3D Systems材料收入占比约30%。",ez:"卖打印材料"},
  {rank:30,cat:'biz',term:"服务外包",pro:"企业将打印需求外包给专业服务商。Sculpteo年处理超100万件零件。",ez:"外包打印"},
  {rank:31,cat:'biz',term:"软件订阅",pro:"切片软件、管理平台按月收费。Autodesk Netfabb订阅费约3000元/年。",ez:"软件月租"},
  {rank:32,cat:'biz',term:"定制化生产",pro:"批量生产个性化产品，如Invisalign隐形牙套，每年生产数百万个定制牙套。",ez:"批量定制"},
  {rank:33,cat:'biz',term:"开源硬件",pro:"RepRap项目推动，Prusa打印机开源，成本低，社区活跃，占桌面市场20%。",ez:"开源打印机"},
  {rank:34,cat:'biz',term:"B2B平台",pro:"连接买家与打印服务商，如Xometry 2023年营收4.6亿美元，撮合交易抽成。",ez:"打印版淘宝"},
  {rank:35,cat:'biz',term:"知识产权风险",pro:"3D打印易侵权，Shapeways曾因侵权下架数千模型，法律保护尚不完善。",ez:"盗版打印风险"},
  {rank:36,cat:'finance',term:"毛利率",pro:"设备商毛利率约50-60%，材料商可达70%。Stratasys 2023年毛利率49.2%。",ez:"毛利润占比"},
  {rank:37,cat:'finance',term:"研发投入占比",pro:"行业平均15-20%。EOS每年研发投入超1亿欧元，占营收18%。",ez:"研发花钱比例"},
  {rank:38,cat:'finance',term:"设备利用率",pro:"工业机利用率影响盈利，理想状态80%以上，Shapeways曾仅40%导致亏损。",ez:"机器开工率"},
  {rank:39,cat:'finance',term:"单件成本",pro:"包括材料、人工、设备折旧。金属打印零件成本约50-500元/件，批量后下降。",ez:"打印一个多少钱"},
  {rank:40,cat:'finance',term:"回收期",pro:"购买工业3D打印机回本时间，通常2-4年，取决于使用率和零件价值。",ez:"回本时间"}
];
